<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="Results (powered by Planemo)"
           tests="44"
           errors="8"
           failures="5"
           skip="0">
    
    <testcase classname="bcftools_norm (Test #1)" name="0" time="40.36085343360901">
        
            
            <system-out><![CDATA[
            
            ]]></system-out>
            <system-err><![CDATA[
            Lines   total/split/realigned/skipped:21/0/13/0
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="bcftools_norm (Test #2)" name="1" time="">
        
            <error type="error" message=""><![CDATA[
                { "status": "skip", "test_index": 1, "tool_id": "bcftools_norm", "tool_version": "1.15.1+galaxy4"}
            ]]></error>
        
    </testcase>
    
    <testcase classname="bcftools_norm (Test #3)" name="2" time="30.637279272079468">
        
            
            <system-out><![CDATA[
            
            ]]></system-out>
            <system-err><![CDATA[
            Lines   total/split/realigned/skipped:19/7/0/0
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="bcftools_norm (Test #4)" name="3" time="31.551583766937256">
        
            
            <system-out><![CDATA[
            
            ]]></system-out>
            <system-err><![CDATA[
            Lines   total/split/realigned/skipped:19/7/19/0
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="bcftools_norm (Test #5)" name="4" time="31.159870624542236">
        
            
            <system-out><![CDATA[
            
            ]]></system-out>
            <system-err><![CDATA[
            Lines   total/split/realigned/skipped:26/0/0/0
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="bcftools_norm (Test #6)" name="5" time="32.69688963890076">
        
            
            <system-out><![CDATA[
            
            ]]></system-out>
            <system-err><![CDATA[
            Lines   total/split/realigned/skipped:26/0/0/0
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="bcftools_norm (Test #7)" name="6" time="32.727952003479004">
        
            
            <system-out><![CDATA[
            
            ]]></system-out>
            <system-err><![CDATA[
            Lines   total/split/realigned/skipped:8/0/0/0REF/ALT total/modified/added:  8/5/3
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="bcftools_norm (Test #8)" name="7" time="17.692641973495483">
        
            <error type="error" message="Input staging problem: Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 1436, in verify_tool
    stage_data_in_history(
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 175, in stage_data_in_history
    staging_interface.handle_jobs()
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 212, in handle_jobs
    self.galaxy_interactor.wait_for_job(job_response["id"], job_response["history_id"], self.maxseconds)
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 399, in wait_for_job
    self.wait_for(lambda: self.__job_ready(job_id, history_id), maxseconds=maxseconds)
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 403, in wait_for
    wait_on(func, what, walltime_exceeded)
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/wait.py", line 38, in wait_on
    value = function()
            ^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 399, in <lambda>
    self.wait_for(lambda: self.__job_ready(job_id, history_id), maxseconds=maxseconds)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 749, in __job_ready
    return self._state_ready(job_id, error_msg="Job in error state.")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 841, in _state_ready
    raise Exception(
Exception: Job in error state.. tool_id: __DATA_FETCH__, exit_code: None, stderr: .
"><![CDATA[
                { "execution_problem": "Input staging problem: Traceback (most recent call last):\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 1436, in verify_tool\n    stage_data_in_history(\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 175, in stage_data_in_history\n    staging_interface.handle_jobs()\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 212, in handle_jobs\n    self.galaxy_interactor.wait_for_job(job_response[\"id\"], job_response[\"history_id\"], self.maxseconds)\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 399, in wait_for_job\n    self.wait_for(lambda: self.__job_ready(job_id, history_id), maxseconds=maxseconds)\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 403, in wait_for\n    wait_on(func, what, walltime_exceeded)\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/wait.py\", line 38, in wait_on\n    value = function()\n            ^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 399, in \u003clambda\u003e\n    self.wait_for(lambda: self.__job_ready(job_id, history_id), maxseconds=maxseconds)\n                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 749, in __job_ready\n    return self._state_ready(job_id, error_msg=\"Job in error state.\")\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 841, in _state_ready\n    raise Exception(\nException: Job in error state.. tool_id: __DATA_FETCH__, exit_code: None, stderr: .\n", "status": "error", "test_index": 7, "time_seconds": 17.692641973495483, "tool_id": "bcftools_norm", "tool_version": "1.15.1+galaxy4"}
            ]]></error>
        
    </testcase>
    
    <testcase classname="bcftools_norm (Test #9)" name="8" time="">
        
            <error type="error" message=""><![CDATA[
                { "status": "skip", "test_index": 8, "tool_id": "bcftools_norm", "tool_version": "1.15.1+galaxy4"}
            ]]></error>
        
    </testcase>
    
    <testcase classname="bcftools_plugin_fill_tags (Test #1)" name="0" time="38.057427167892456">
        
            
            <system-out><![CDATA[
            
            ]]></system-out>
            <system-err><![CDATA[
            
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="bcftools_plugin_fill_tags (Test #2)" name="1" time="32.64952373504639">
        
            
            <system-out><![CDATA[
            
            ]]></system-out>
            <system-err><![CDATA[
            
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="circos (Test #1)" name="0" time="76.4195237159729">
        
            
            <system-out><![CDATA[
            debuggroup summary 0.12s welcome to circos v0.69-8 15 Jun 2019 on Perl 5.032001debuggroup summary 0.13s current working directory /galaxy/server/database/jobs_directory/000/104/workingdebuggroup summary 0.13s command /usr/local/bin/circos -conf circos/conf/circos.conf -noparanoiddebuggroup summary 0.13s loading configuration from file circos/conf/circos.confdebuggroup summary 0.13s found conf file circos/conf/circos.confdebuggroup summary 0.23s debug will appear for these features: output,summarydebuggroup summary 0.23s bitmap output image ./circos.pngdebuggroup summary 0.23s SVG output image ./circos.svgdebuggroup summary 0.23s parsing karyotype and organizing ideogramsdebuggroup summary 0.23s karyotype has 2 chromosomes of total size 56,082debuggroup summary 0.23s applying global and local scalingdebuggroup summary 0.24s allocating image, colors and brushesdebuggroup summary 4.74s drawing 2 ideograms of total size 56,082debuggroup summary 4.74s drawing highlights and ideogramsdebuggroup output 4.75s generating outputdebuggroup output 5.06s created PNG image ./circos.png (40 kb)debuggroup output 5.06s created SVG image ./circos.svg (2 kb)
            ]]></system-out>
            <system-err><![CDATA[
            Use of uninitialized value in subroutine entry at /usr/local/bin/../lib/Circos/Configuration.pm line 781.
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="circos (Test #2)" name="1" time="40.43224263191223">
        
            
                <error type="error" message="Tool exit code: None"><![CDATA[
                    { "inputs": {  "ideogram|units": "kb",  "outputs|svg": true,  "reference_genome|ref|genome_fasta": {   "id": "9f469a39167756cd",   "src": "hda"  },  "reference_genome|ref|ref_source": "history",  "sec_links|data_0|data_source": {   "id": "2a97063ac888f520",   "src": "hda"  },  "sec_links|data_0|linktype|ribbon": "yes",  "sec_links|data_0|radius": "0.59",  "sec_tdd|data_0|plot_format|data_source": {   "id": "b8e48a4d30e4786a",   "src": "hda"  },  "sec_tdd|data_0|plot_format|plot_format_select": "histogram",  "sec_tdd|data_0|r0": "0.8",  "sec_tdd|data_0|r1": "0.9",  "sec_tdd|data_1|plot_format|data_source": {   "id": "b8e48a4d30e4786a",   "src": "hda"  },  "sec_tdd|data_1|plot_format|plot_format_select": "scatter",  "sec_tdd|data_1|r0": "0.7",  "sec_tdd|data_1|r1": "0.8",  "sec_tdd|data_2|plot_format|data_source": {   "id": "95280ddbc094082b",   "src": "hda"  },  "sec_tdd|data_2|plot_format|plot_format_select": "tile",  "sec_tdd|data_2|r0": "0.6",  "sec_tdd|data_2|r1": "0.7",  "ticks|tick_group_0|spacing": "1",  "ticks|tick_group_1|spacing": "5",  "ticks|tick_group_1|ticks|format": "%.1f",  "ticks|tick_group_1|ticks|show_tick_labels": "yes" }, "job": {  "command_line": "mkdir -p circos/conf/ circos/data/ \u0026\u0026  ln -s \u0027/galaxy/server/database/objects/e/4/c/dataset_e4c686b8-e8bf-436f-9a27-b43997801fd1.dat\u0027 genomeref.fa \u0026\u0026  python \u0027/cvmfs/cloud.galaxyproject.org/tools/toolshed.g2.bx.psu.edu/repos/iuc/circos/df7356989ac1/circos/karyotype-from-fasta.py\u0027 genomeref.fa \u003e circos/conf/karyotype.txt \u0026\u0026  python \u0027/cvmfs/cloud.galaxyproject.org/tools/toolshed.g2.bx.psu.edu/repos/iuc/circos/df7356989ac1/circos/karyotype-colors.py\u0027 `grep -c \u0027^chr\\s\u0027 \u0027circos/conf/karyotype.txt\u0027` \u003e \u0027circos/conf/karyotype-colors.conf\u0027 \u0026\u0026  touch circos/conf/karyotype-colors.conf \u0026\u0026    cp \u0027/galaxy/server/database/jobs_directory/000/109/configs/tmpdsihwlrw\u0027 circos/conf/circos.conf \u0026\u0026 cp \u0027/galaxy/server/database/jobs_directory/000/109/configs/tmpc309nv4p\u0027 circos/conf/ticks.conf \u0026\u0026 cp \u0027/galaxy/server/database/jobs_directory/000/109/configs/tmp1xrnqymr\u0027 circos/conf/ideogram.conf \u0026\u0026 cp \u0027/galaxy/server/database/jobs_directory/000/109/configs/tmph7xetrur\u0027  circos/conf/data.conf \u0026\u0026 cp \u0027/galaxy/server/database/jobs_directory/000/109/configs/tmpuq0p46q_\u0027  circos/conf/links.conf \u0026\u0026 cp \u0027/galaxy/server/database/jobs_directory/000/109/configs/tmpalv634kh\u0027 circos/conf/galaxy_test_case.json \u0026\u0026  cp \u0027/galaxy/server/database/objects/6/3/8/dataset_638c52ae-4a1c-4f2a-bb98-fac55d8195f6.dat\u0027 circos/data/data-0.txt \u0026\u0026 cp \u0027/galaxy/server/database/objects/6/3/8/dataset_638c52ae-4a1c-4f2a-bb98-fac55d8195f6.dat\u0027 circos/data/data-1.txt \u0026\u0026 cp \u0027/galaxy/server/database/objects/7/b/f/dataset_7bfe6e12-8ee3-4149-8b73-f5ad7253644c.dat\u0027 circos/data/data-2.txt \u0026\u0026  cp \u0027/galaxy/server/database/objects/b/0/8/dataset_b088bc21-0644-45ae-8a1a-81c28ec12475.dat\u0027 circos/data/links-0.txt \u0026\u0026   circos -conf circos/conf/circos.conf -noparanoid",  "command_version": null,  "copied_from_job_id": null,  "create_time": "2025-08-14T01:25:59.172929",  "dependencies": [],  "exit_code": null,  "external_id": "gxy-mgzqj",  "galaxy_version": "24.1",  "handler": null,  "history_id": "56a0493b6f9a16b3",  "id": "3d602f247695b9d8",  "inputs": {   "reference_genome|ref|genome_fasta": {    "id": "9f469a39167756cd",    "src": "hda",    "uuid": "e4c686b8-e8bf-436f-9a27-b43997801fd1"   },   "sec_links|data_0|data_source": {    "id": "2a97063ac888f520",    "src": "hda",    "uuid": "b088bc21-0644-45ae-8a1a-81c28ec12475"   },   "sec_tdd|data_0|plot_format|data_source": {    "id": "b8e48a4d30e4786a",    "src": "hda",    "uuid": "638c52ae-4a1c-4f2a-bb98-fac55d8195f6"   },   "sec_tdd|data_1|plot_format|data_source": {    "id": "b8e48a4d30e4786a",    "src": "hda",    "uuid": "638c52ae-4a1c-4f2a-bb98-fac55d8195f6"   },   "sec_tdd|data_2|plot_format|data_source": {    "id": "95280ddbc094082b",    "src": "hda",    "uuid": "7bfe6e12-8ee3-4149-8b73-f5ad7253644c"   }  },  "job_messages": null,  "job_metrics": [],  "job_runner_name": null,  "job_stderr": null,  "job_stdout": null,  "model_class": "Job",  "output_collections": {},  "outputs": {   "karyotype_txt": {    "id": "ef145579da7e5a0c",    "src": "hda",    "uuid": "4edf6b3d-0b54-4789-881b-6ae404ef656a"   },   "output_png": {    "id": "3ce52520b7493ba7",    "src": "hda",    "uuid": "3c4d21b1-1ecc-41e6-a081-d0b9935546c5"   },   "output_svg": {    "id": "8eba5d48e1ccfdfd",    "src": "hda",    "uuid": "31853a00-5ed7-493c-b60b-95e31e073f4f"   }  },  "params": {   "__input_ext": "\"fasta\"",   "chromInfo": "\"/cvmfs/data.galaxyproject.org/managed/len/ucsc/?.len\"",   "dbkey": "\"?\"",   "ideogram": "{\"angle_offset\": \"-90\", \"angle_orientation\": \"clockwise\", \"bands\": {\"band_stroke_color\": \"#000000\", \"band_stroke_thickness\": \"0\", \"band_transparency\": \"3\", \"fill_bands\": true, \"show_bands\": true}, \"chromosomes_reverse\": null, \"ideogram_labels\": {\"parallel\": true, \"radius_offset\": \"0.075\", \"show_label\": true, \"size\": \"24\"}, \"limit_chromosomes\": null, \"pairwise_spacing\": [], \"radius\": \"0.9\", \"spacing\": \"0.5\", \"thickness\": \"30.0\", \"units\": \"kb\"}",   "limits": "{\"max_ideograms\": \"200\", \"max_links\": \"25000\", \"max_points_per_track\": \"25000\", \"max_ticks\": \"5000\"}",   "outputs": "{\"png\": true, \"svg\": true, \"tar\": false}",   "plot_options": "{\"background\": {\"__current_case__\": 1, \"background_color\": \"#ffffff\", \"background_select\": \"color\"}, \"colour_profile\": null, \"radius\": \"1500\"}",   "reference_genome": "{\"ref\": {\"__current_case__\": 2, \"genome_fasta\": {\"values\": [{\"id\": 125, \"src\": \"hda\"}]}, \"ref_source\": \"history\"}}",   "scaling": "{\"zooms\": []}",   "sec_links": "{\"data\": [{\"__index__\": 0, \"advanced\": {\"bezier_radius_purity\": \"0.75\", \"crest\": \"0.5\", \"perturbation\": {\"__current_case__\": 1, \"perturb\": \"no\"}}, \"bezier_radius\": \"0.1\", \"color\": \"#000000\", \"color_alpha\": \"1.0\", \"data_source\": {\"values\": [{\"id\": 128, \"src\": \"hda\"}]}, \"linktype\": {\"__current_case__\": 0, \"pattern\": \"solid\", \"ribbon\": \"yes\", \"twist\": \"\"}, \"minsize\": \"0.0\", \"radius\": \"0.59\", \"sec_link_rule\": {\"rules\": []}, \"thickness\": \"15.0\", \"zdepth\": \"0\"}]}",   "sec_tdd": "{\"data\": [{\"__index__\": 0, \"minmax\": {\"__current_case__\": 1, \"minmax_select\": \"no\"}, \"minsize\": \"0.0\", \"orientation\": false, \"plot_format\": {\"__current_case__\": 0, \"data_source\": {\"values\": [{\"id\": 126, \"src\": \"hda\"}]}, \"format_specific\": {\"extend_bins\": false, \"fill_color\": \"#ffdcfc\", \"fill_color_alpha\": \"1.0\", \"fill_under\": true, \"stroke_color\": \"#000000\", \"stroke_color_alpha\": \"1.0\", \"stroke_thickness\": \"1\"}, \"plot_format_select\": \"histogram\"}, \"r0\": \"0.8\", \"r1\": \"0.9\", \"sec_axes\": {\"axes\": [], \"only_if_data\": \"always\"}, \"sec_bkgs\": {\"backgrounds\": [], \"only_if_data\": \"always\"}, \"sec_rule\": {\"rules\": []}, \"zdepth\": \"0\"}, {\"__index__\": 1, \"minmax\": {\"__current_case__\": 1, \"minmax_select\": \"no\"}, \"minsize\": \"0.0\", \"orientation\": false, \"plot_format\": {\"__current_case__\": 5, \"data_source\": {\"values\": [{\"id\": 126, \"src\": \"hda\"}]}, \"format_specific\": {\"fill_color\": \"#555555\", \"fill_color_alpha\": \"1.0\", \"glyph\": \"circle\", \"glyph_size\": \"8\", \"stroke_color\": \"#000000\", \"stroke_color_alpha\": \"1.0\", \"stroke_thickness\": \"1\"}, \"plot_format_select\": \"scatter\"}, \"r0\": \"0.7\", \"r1\": \"0.8\", \"sec_axes\": {\"axes\": [], \"only_if_data\": \"always\"}, \"sec_bkgs\": {\"backgrounds\": [], \"only_if_data\": \"always\"}, \"sec_rule\": {\"rules\": []}, \"zdepth\": \"0\"}, {\"__index__\": 2, \"minmax\": {\"__current_case__\": 1, \"minmax_select\": \"no\"}, \"minsize\": \"0.0\", \"orientation\": false, \"plot_format\": {\"__current_case__\": 6, \"data_source\": {\"values\": [{\"id\": 127, \"src\": \"hda\"}]}, \"format_specific\": {\"fill_color\": \"#000000\", \"fill_color_alpha\": \"1.0\", \"layers\": \"15\", \"margin\": \"0.002\", \"overflow\": {\"__current_case__\": 0, \"overflow_behavior\": \"hide\"}, \"padding\": \"8.0\", \"stroke_color\": \"#000000\", \"stroke_color_alpha\": \"1.0\", \"stroke_thickness\": \"1\", \"thickness\": \"15.0\"}, \"plot_format_select\": \"tile\"}, \"r0\": \"0.6\", \"r1\": \"0.7\", \"sec_axes\": {\"axes\": [], \"only_if_data\": \"always\"}, \"sec_bkgs\": {\"backgrounds\": [], \"only_if_data\": \"always\"}, \"sec_rule\": {\"rules\": []}, \"zdepth\": \"0\"}]}",   "ticks": "{\"radius\": \"1.0\", \"skip_first_label\": false, \"skip_last_label\": false, \"tick_group\": [{\"__index__\": 0, \"color\": \"#000000\", \"size\": \"10.0\", \"spacing\": \"1.0\", \"ticks\": {\"__current_case__\": 1, \"show_tick_labels\": \"no\"}}, {\"__index__\": 1, \"color\": \"#000000\", \"size\": \"10.0\", \"spacing\": \"5.0\", \"ticks\": {\"__current_case__\": 0, \"format\": \"%.1f\", \"format_ext\": true, \"label_offset\": \"10.0\", \"label_size\": \"20.0\", \"show_tick_labels\": \"yes\"}}]}"  },  "state": "error",  "stderr": "Use of uninitialized value in subroutine entry at /usr/local/bin/../lib/Circos/Configuration.pm line 781.\nUse of uninitialized value in subroutine entry at /usr/local/bin/../lib/Circos/Configuration.pm line 781.\nUse of uninitialized value within %Circos::Error::GROUPERROR in uc at /usr/local/bin/../lib/Circos/Error.pm line 354, \u003cF\u003e line 21.\nUse of uninitialized value within %Circos::Error::GROUPERROR in uc at /usr/local/bin/../lib/Circos/Error.pm line 354, \u003cF\u003e line 21.\nUse of uninitialized value in subroutine entry at /usr/local/bin/../lib/Circos/Configuration.pm line 781, \u003cF\u003e line 21.\nUse of uninitialized value in subroutine entry at /usr/local/bin/../lib/Circos/Configuration.pm line 781.\nUse of uninitialized value in subroutine entry at /usr/local/bin/../lib/Circos/Configuration.pm line 781.\nUse of uninitialized value in subroutine entry at /usr/local/bin/../lib/Circos/Configuration.pm line 781, \u003cF\u003e line 1214.\nUse of uninitialized value in subroutine entry at /usr/local/bin/../lib/Circos/Configuration.pm line 781.\nUse of uninitialized value in subroutine entry at /usr/local/bin/../lib/Circos/Configuration.pm line 781.\nUse of uninitialized value within %Circos::Error::GROUPERROR in uc at /usr/local/bin/../lib/Circos/Error.pm line 354.\n",  "stdout": "debuggroup summary 0.12s welcome to circos v0.69-8 15 Jun 2019 on Perl 5.032001\ndebuggroup summary 0.12s current working directory /galaxy/server/database/jobs_directory/000/109/working\ndebuggroup summary 0.12s command /usr/local/bin/circos -conf circos/conf/circos.conf -noparanoid\ndebuggroup summary 0.12s loading configuration from file circos/conf/circos.conf\ndebuggroup summary 0.13s found conf file circos/conf/circos.conf\ndebuggroup summary 0.23s debug will appear for these features: output,summary\ndebuggroup summary 0.23s bitmap output image ./circos.png\ndebuggroup summary 0.23s SVG output image ./circos.svg\ndebuggroup summary 0.23s parsing karyotype and organizing ideograms\ndebuggroup summary 0.23s karyotype has 2 chromosomes of total size 56,082\ndebuggroup summary 0.23s applying global and local scaling\ndebuggroup summary 0.24s allocating image, colors and brushes\ndebuggroup summary 4.65s drawing 2 ideograms of total size 56,082\ndebuggroup summary 4.65s drawing highlights and ideograms\ndebuggroup summary 4.68s found conf file /usr/local/bin/../etc/tracks/link.conf\ndebuggroup summary 4.68s process track_0 link circos/conf/../data/links-0.txt\ndebuggroup summary 4.69s drawing link track_0 z 0\ndebuggroup !circoswarning 4.72s  Data point of type [link] [50000-50500] extended past end of ideogram [ctgA 0-50001]. This data point will be [trimmed].\ndebuggroup !circoswarning 4.72s  Data point of type [link] [51000-51500] extended past end of ideogram [ctgA 0-50001]. This data point will be [hidden].\ndebuggroup summary 4.72s found conf file /usr/local/bin/../etc/tracks/histogram.conf\ndebuggroup summary 4.72s found conf file /usr/local/bin/../etc/tracks/scatter.conf\ndebuggroup summary 4.72s found conf file /usr/local/bin/../etc/tracks/tile.conf\ndebuggroup summary 4.72s processing track_0 histogram circos/conf/../data/data-0.txt\ndebuggroup summary 4.78s processing track_1 scatter circos/conf/../data/data-1.txt\ndebuggroup summary 4.94s processing track_2 tile circos/conf/../data/data-2.txt\ndebuggroup summary 4.95s drawing track_0 histogram z 0 data-0.txt orient out\ndebuggroup summary 4.96s found conf file /usr/local/bin/../etc/tracks/axis.conf\ndebuggroup summary 5.40s drawing track_1 scatter z 0 data-1.txt orient out\ndebuggroup summary 5.42s found conf file /usr/local/bin/../etc/tracks/axis.conf\ndebuggroup summary 5.55s drawing track_2 tile z 0 data-2.txt orient out\ndebuggroup summary 5.55s found conf file /usr/local/bin/../etc/tracks/axis.conf\ndebuggroup !circoswarning 5.68s  Data point of type [tile] [3013-6130] extended past end of ideogram [ctgB 0-6079]. This data point will be [trimmed].\ndebuggroup output 5.68s generating output\ndebuggroup output 6.05s created PNG image ./circos.png (539 kb)\ndebuggroup output 6.06s created SVG image ./circos.svg (414 kb)\n",  "tool_id": "toolshed.g2.bx.psu.edu/repos/iuc/circos/circos/0.69.8+galaxy7",  "tool_stderr": "Use of uninitialized value in subroutine entry at /usr/local/bin/../lib/Circos/Configuration.pm line 781.\nUse of uninitialized value in subroutine entry at /usr/local/bin/../lib/Circos/Configuration.pm line 781.\nUse of uninitialized value within %Circos::Error::GROUPERROR in uc at /usr/local/bin/../lib/Circos/Error.pm line 354, \u003cF\u003e line 21.\nUse of uninitialized value within %Circos::Error::GROUPERROR in uc at /usr/local/bin/../lib/Circos/Error.pm line 354, \u003cF\u003e line 21.\nUse of uninitialized value in subroutine entry at /usr/local/bin/../lib/Circos/Configuration.pm line 781, \u003cF\u003e line 21.\nUse of uninitialized value in subroutine entry at /usr/local/bin/../lib/Circos/Configuration.pm line 781.\nUse of uninitialized value in subroutine entry at /usr/local/bin/../lib/Circos/Configuration.pm line 781.\nUse of uninitialized value in subroutine entry at /usr/local/bin/../lib/Circos/Configuration.pm line 781, \u003cF\u003e line 1214.\nUse of uninitialized value in subroutine entry at /usr/local/bin/../lib/Circos/Configuration.pm line 781.\nUse of uninitialized value in subroutine entry at /usr/local/bin/../lib/Circos/Configuration.pm line 781.\nUse of uninitialized value within %Circos::Error::GROUPERROR in uc at /usr/local/bin/../lib/Circos/Error.pm line 354.\n",  "tool_stdout": "debuggroup summary 0.12s welcome to circos v0.69-8 15 Jun 2019 on Perl 5.032001\ndebuggroup summary 0.12s current working directory /galaxy/server/database/jobs_directory/000/109/working\ndebuggroup summary 0.12s command /usr/local/bin/circos -conf circos/conf/circos.conf -noparanoid\ndebuggroup summary 0.12s loading configuration from file circos/conf/circos.conf\ndebuggroup summary 0.13s found conf file circos/conf/circos.conf\ndebuggroup summary 0.23s debug will appear for these features: output,summary\ndebuggroup summary 0.23s bitmap output image ./circos.png\ndebuggroup summary 0.23s SVG output image ./circos.svg\ndebuggroup summary 0.23s parsing karyotype and organizing ideograms\ndebuggroup summary 0.23s karyotype has 2 chromosomes of total size 56,082\ndebuggroup summary 0.23s applying global and local scaling\ndebuggroup summary 0.24s allocating image, colors and brushes\ndebuggroup summary 4.65s drawing 2 ideograms of total size 56,082\ndebuggroup summary 4.65s drawing highlights and ideograms\ndebuggroup summary 4.68s found conf file /usr/local/bin/../etc/tracks/link.conf\ndebuggroup summary 4.68s process track_0 link circos/conf/../data/links-0.txt\ndebuggroup summary 4.69s drawing link track_0 z 0\ndebuggroup !circoswarning 4.72s  Data point of type [link] [50000-50500] extended past end of ideogram [ctgA 0-50001]. This data point will be [trimmed].\ndebuggroup !circoswarning 4.72s  Data point of type [link] [51000-51500] extended past end of ideogram [ctgA 0-50001]. This data point will be [hidden].\ndebuggroup summary 4.72s found conf file /usr/local/bin/../etc/tracks/histogram.conf\ndebuggroup summary 4.72s found conf file /usr/local/bin/../etc/tracks/scatter.conf\ndebuggroup summary 4.72s found conf file /usr/local/bin/../etc/tracks/tile.conf\ndebuggroup summary 4.72s processing track_0 histogram circos/conf/../data/data-0.txt\ndebuggroup summary 4.78s processing track_1 scatter circos/conf/../data/data-1.txt\ndebuggroup summary 4.94s processing track_2 tile circos/conf/../data/data-2.txt\ndebuggroup summary 4.95s drawing track_0 histogram z 0 data-0.txt orient out\ndebuggroup summary 4.96s found conf file /usr/local/bin/../etc/tracks/axis.conf\ndebuggroup summary 5.40s drawing track_1 scatter z 0 data-1.txt orient out\ndebuggroup summary 5.42s found conf file /usr/local/bin/../etc/tracks/axis.conf\ndebuggroup summary 5.55s drawing track_2 tile z 0 data-2.txt orient out\ndebuggroup summary 5.55s found conf file /usr/local/bin/../etc/tracks/axis.conf\ndebuggroup !circoswarning 5.68s  Data point of type [tile] [3013-6130] extended past end of ideogram [ctgB 0-6079]. This data point will be [trimmed].\ndebuggroup output 5.68s generating output\ndebuggroup output 6.05s created PNG image ./circos.png (539 kb)\ndebuggroup output 6.06s created SVG image ./circos.svg (414 kb)\n",  "update_time": "2025-08-14T01:26:10.827313",  "user_email": "tests@fake.org" }, "output_problems": [  "Job in error state.. tool_id: toolshed.g2.bx.psu.edu/repos/iuc/circos/circos/0.69.8+galaxy7, exit_code: None, stderr: Use of uninitialized value in subroutine entry at /usr/local/bin/../lib/Circos/Configuration.pm line 781.\nUse of uninitialized value in subroutine entry at /usr/local/bin/../lib/Circos/Configuration.pm line 781.\nUse of uninitialized value within %Circos::Error::GROUPERROR in uc at /usr/local/bin/../lib/Circos/Error.pm line 354, \u003cF\u003e line 21.\nUse of uninitialized value within %Circos::Error::GROUPERROR in uc at /usr/local/bin/../lib/Circos/Error.pm line 354, \u003cF\u003e line 21.\nUse of uninitialized value in subroutine entry at /usr/local/bin/../lib/Circos/Configuration.pm line 781, \u003cF\u003e line 21.\nUse of uninitialized value in subroutine entry at /usr/local/bin/../lib/Circos/Configuration.pm line 781.\nUse of uninitialized value in subroutine entry at /usr/local/bin/../lib/Circos/Configuration.pm line 781.\nUse of uninitialized value in subroutine entry at /usr/local/bin/../lib/Circos/Configuration.pm line 781, \u003cF\u003e line 1214.\nUse of uninitialized value in subroutine entry at /usr/local/bin/../lib/Circos/Configuration.pm line 781.\nUse of uninitialized value in subroutine entry at /usr/local/bin/../lib/Circos/Configuration.pm line 781.\nUse of uninitialized value within %Circos::Error::GROUPERROR in uc at /usr/local/bin/../lib/Circos/Error.pm line 354.\n.",  "Job in error state.. tool_id: toolshed.g2.bx.psu.edu/repos/iuc/circos/circos/0.69.8+galaxy7, exit_code: None, stderr: Use of uninitialized value in subroutine entry at /usr/local/bin/../lib/Circos/Configuration.pm line 781.\nUse of uninitialized value in subroutine entry at /usr/local/bin/../lib/Circos/Configuration.pm line 781.\nUse of uninitialized value within %Circos::Error::GROUPERROR in uc at /usr/local/bin/../lib/Circos/Error.pm line 354, \u003cF\u003e line 21.\nUse of uninitialized value within %Circos::Error::GROUPERROR in uc at /usr/local/bin/../lib/Circos/Error.pm line 354, \u003cF\u003e line 21.\nUse of uninitialized value in subroutine entry at /usr/local/bin/../lib/Circos/Configuration.pm line 781, \u003cF\u003e line 21.\nUse of uninitialized value in subroutine entry at /usr/local/bin/../lib/Circos/Configuration.pm line 781.\nUse of uninitialized value in subroutine entry at /usr/local/bin/../lib/Circos/Configuration.pm line 781.\nUse of uninitialized value in subroutine entry at /usr/local/bin/../lib/Circos/Configuration.pm line 781, \u003cF\u003e line 1214.\nUse of uninitialized value in subroutine entry at /usr/local/bin/../lib/Circos/Configuration.pm line 781.\nUse of uninitialized value in subroutine entry at /usr/local/bin/../lib/Circos/Configuration.pm line 781.\nUse of uninitialized value within %Circos::Error::GROUPERROR in uc at /usr/local/bin/../lib/Circos/Error.pm line 354.\n.",  "Job in error state.. tool_id: toolshed.g2.bx.psu.edu/repos/iuc/circos/circos/0.69.8+galaxy7, exit_code: None, stderr: Use of uninitialized value in subroutine entry at /usr/local/bin/../lib/Circos/Configuration.pm line 781.\nUse of uninitialized value in subroutine entry at /usr/local/bin/../lib/Circos/Configuration.pm line 781.\nUse of uninitialized value within %Circos::Error::GROUPERROR in uc at /usr/local/bin/../lib/Circos/Error.pm line 354, \u003cF\u003e line 21.\nUse of uninitialized value within %Circos::Error::GROUPERROR in uc at /usr/local/bin/../lib/Circos/Error.pm line 354, \u003cF\u003e line 21.\nUse of uninitialized value in subroutine entry at /usr/local/bin/../lib/Circos/Configuration.pm line 781, \u003cF\u003e line 21.\nUse of uninitialized value in subroutine entry at /usr/local/bin/../lib/Circos/Configuration.pm line 781.\nUse of uninitialized value in subroutine entry at /usr/local/bin/../lib/Circos/Configuration.pm line 781.\nUse of uninitialized value in subroutine entry at /usr/local/bin/../lib/Circos/Configuration.pm line 781, \u003cF\u003e line 1214.\nUse of uninitialized value in subroutine entry at /usr/local/bin/../lib/Circos/Configuration.pm line 781.\nUse of uninitialized value in subroutine entry at /usr/local/bin/../lib/Circos/Configuration.pm line 781.\nUse of uninitialized value within %Circos::Error::GROUPERROR in uc at /usr/local/bin/../lib/Circos/Error.pm line 354.\n." ], "status": "failure", "test_index": 1, "time_seconds": 40.43224263191223, "tool_id": "circos", "tool_version": "0.69.8+galaxy7"}
                ]]></error>
            
            <system-out><![CDATA[
            debuggroup summary 0.12s welcome to circos v0.69-8 15 Jun 2019 on Perl 5.032001debuggroup summary 0.12s current working directory /galaxy/server/database/jobs_directory/000/109/workingdebuggroup summary 0.12s command /usr/local/bin/circos -conf circos/conf/circos.conf -noparanoiddebuggroup summary 0.12s loading configuration from file circos/conf/circos.confdebuggroup summary 0.13s found conf file circos/conf/circos.confdebuggroup summary 0.23s debug will appear for these features: output,summarydebuggroup summary 0.23s bitmap output image ./circos.pngdebuggroup summary 0.23s SVG output image ./circos.svgdebuggroup summary 0.23s parsing karyotype and organizing ideogramsdebuggroup summary 0.23s karyotype has 2 chromosomes of total size 56,082debuggroup summary 0.23s applying global and local scalingdebuggroup summary 0.24s allocating image, colors and brushesdebuggroup summary 4.65s drawing 2 ideograms of total size 56,082debuggroup summary 4.65s drawing highlights and ideogramsdebuggroup summary 4.68s found conf file /usr/local/bin/../etc/tracks/link.confdebuggroup summary 4.68s process track_0 link circos/conf/../data/links-0.txtdebuggroup summary 4.69s drawing link track_0 z 0debuggroup !circoswarning 4.72s  Data point of type [link] [50000-50500] extended past end of ideogram [ctgA 0-50001]. This data point will be [trimmed].debuggroup !circoswarning 4.72s  Data point of type [link] [51000-51500] extended past end of ideogram [ctgA 0-50001]. This data point will be [hidden].debuggroup summary 4.72s found conf file /usr/local/bin/../etc/tracks/histogram.confdebuggroup summary 4.72s found conf file /usr/local/bin/../etc/tracks/scatter.confdebuggroup summary 4.72s found conf file /usr/local/bin/../etc/tracks/tile.confdebuggroup summary 4.72s processing track_0 histogram circos/conf/../data/data-0.txtdebuggroup summary 4.78s processing track_1 scatter circos/conf/../data/data-1.txtdebuggroup summary 4.94s processing track_2 tile circos/conf/../data/data-2.txtdebuggroup summary 4.95s drawing track_0 histogram z 0 data-0.txt orient outdebuggroup summary 4.96s found conf file /usr/local/bin/../etc/tracks/axis.confdebuggroup summary 5.40s drawing track_1 scatter z 0 data-1.txt orient outdebuggroup summary 5.42s found conf file /usr/local/bin/../etc/tracks/axis.confdebuggroup summary 5.55s drawing track_2 tile z 0 data-2.txt orient outdebuggroup summary 5.55s found conf file /usr/local/bin/../etc/tracks/axis.confdebuggroup !circoswarning 5.68s  Data point of type [tile] [3013-6130] extended past end of ideogram [ctgB 0-6079]. This data point will be [trimmed].debuggroup output 5.68s generating outputdebuggroup output 6.05s created PNG image ./circos.png (539 kb)debuggroup output 6.06s created SVG image ./circos.svg (414 kb)
            ]]></system-out>
            <system-err><![CDATA[
            Use of uninitialized value in subroutine entry at /usr/local/bin/../lib/Circos/Configuration.pm line 781.Use of uninitialized value in subroutine entry at /usr/local/bin/../lib/Circos/Configuration.pm line 781.Use of uninitialized value within %Circos::Error::GROUPERROR in uc at /usr/local/bin/../lib/Circos/Error.pm line 354, <F> line 21.Use of uninitialized value within %Circos::Error::GROUPERROR in uc at /usr/local/bin/../lib/Circos/Error.pm line 354, <F> line 21.Use of uninitialized value in subroutine entry at /usr/local/bin/../lib/Circos/Configuration.pm line 781, <F> line 21.Use of uninitialized value in subroutine entry at /usr/local/bin/../lib/Circos/Configuration.pm line 781.Use of uninitialized value in subroutine entry at /usr/local/bin/../lib/Circos/Configuration.pm line 781.Use of uninitialized value in subroutine entry at /usr/local/bin/../lib/Circos/Configuration.pm line 781, <F> line 1214.Use of uninitialized value in subroutine entry at /usr/local/bin/../lib/Circos/Configuration.pm line 781.Use of uninitialized value in subroutine entry at /usr/local/bin/../lib/Circos/Configuration.pm line 781.Use of uninitialized value within %Circos::Error::GROUPERROR in uc at /usr/local/bin/../lib/Circos/Error.pm line 354.
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="deeptools_plot_enrichment (Test #1)" name="0" time="56.26912474632263">
        
            
            <system-out><![CDATA[
            
            ]]></system-out>
            <system-err><![CDATA[
            
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="filter_tabular (Test #1)" name="0" time="73.37181830406189">
        
            
            <system-out><![CDATA[
            
            ]]></system-out>
            <system-err><![CDATA[
            
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="filter_tabular (Test #2)" name="1" time="32.42361354827881">
        
            
            <system-out><![CDATA[
            
            ]]></system-out>
            <system-err><![CDATA[
            
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="filter_tabular (Test #3)" name="2" time="32.95617938041687">
        
            
            <system-out><![CDATA[
            
            ]]></system-out>
            <system-err><![CDATA[
            
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="filter_tabular (Test #4)" name="3" time="32.329023599624634">
        
            
            <system-out><![CDATA[
            
            ]]></system-out>
            <system-err><![CDATA[
            
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="filter_tabular (Test #5)" name="4" time="28.978909254074097">
        
            
            <system-out><![CDATA[
            
            ]]></system-out>
            <system-err><![CDATA[
            
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="flash (Test #1)" name="0" time="40.6571900844574">
        
            
            <system-out><![CDATA[
            
            ]]></system-out>
            <system-err><![CDATA[
            
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="flash (Test #2)" name="1" time="41.23176550865173">
        
            
            <system-out><![CDATA[
            
            ]]></system-out>
            <system-err><![CDATA[
            
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="flash (Test #3)" name="2" time="11.029984712600708">
        
            <error type="error" message="Input staging problem: Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 1436, in verify_tool
    stage_data_in_history(
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 175, in stage_data_in_history
    staging_interface.handle_jobs()
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 212, in handle_jobs
    self.galaxy_interactor.wait_for_job(job_response["id"], job_response["history_id"], self.maxseconds)
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 399, in wait_for_job
    self.wait_for(lambda: self.__job_ready(job_id, history_id), maxseconds=maxseconds)
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 403, in wait_for
    wait_on(func, what, walltime_exceeded)
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/wait.py", line 38, in wait_on
    value = function()
            ^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 399, in <lambda>
    self.wait_for(lambda: self.__job_ready(job_id, history_id), maxseconds=maxseconds)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 749, in __job_ready
    return self._state_ready(job_id, error_msg="Job in error state.")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 841, in _state_ready
    raise Exception(
Exception: Job in error state.. tool_id: __DATA_FETCH__, exit_code: None, stderr: .
"><![CDATA[
                { "execution_problem": "Input staging problem: Traceback (most recent call last):\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 1436, in verify_tool\n    stage_data_in_history(\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 175, in stage_data_in_history\n    staging_interface.handle_jobs()\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 212, in handle_jobs\n    self.galaxy_interactor.wait_for_job(job_response[\"id\"], job_response[\"history_id\"], self.maxseconds)\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 399, in wait_for_job\n    self.wait_for(lambda: self.__job_ready(job_id, history_id), maxseconds=maxseconds)\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 403, in wait_for\n    wait_on(func, what, walltime_exceeded)\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/wait.py\", line 38, in wait_on\n    value = function()\n            ^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 399, in \u003clambda\u003e\n    self.wait_for(lambda: self.__job_ready(job_id, history_id), maxseconds=maxseconds)\n                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 749, in __job_ready\n    return self._state_ready(job_id, error_msg=\"Job in error state.\")\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 841, in _state_ready\n    raise Exception(\nException: Job in error state.. tool_id: __DATA_FETCH__, exit_code: None, stderr: .\n", "status": "error", "test_index": 2, "time_seconds": 11.029984712600708, "tool_id": "flash", "tool_version": "1.2.11.4"}
            ]]></error>
        
    </testcase>
    
    <testcase classname="flash (Test #4)" name="3" time="35.00329351425171">
        
            
            <system-out><![CDATA[
            
            ]]></system-out>
            <system-err><![CDATA[
            
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="flash (Test #5)" name="4" time="10.913183450698853">
        
            <error type="error" message="Input staging problem: Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 1436, in verify_tool
    stage_data_in_history(
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 175, in stage_data_in_history
    staging_interface.handle_jobs()
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 212, in handle_jobs
    self.galaxy_interactor.wait_for_job(job_response["id"], job_response["history_id"], self.maxseconds)
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 399, in wait_for_job
    self.wait_for(lambda: self.__job_ready(job_id, history_id), maxseconds=maxseconds)
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 403, in wait_for
    wait_on(func, what, walltime_exceeded)
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/wait.py", line 38, in wait_on
    value = function()
            ^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 399, in <lambda>
    self.wait_for(lambda: self.__job_ready(job_id, history_id), maxseconds=maxseconds)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 749, in __job_ready
    return self._state_ready(job_id, error_msg="Job in error state.")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 841, in _state_ready
    raise Exception(
Exception: Job in error state.. tool_id: __DATA_FETCH__, exit_code: None, stderr: .
"><![CDATA[
                { "execution_problem": "Input staging problem: Traceback (most recent call last):\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 1436, in verify_tool\n    stage_data_in_history(\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 175, in stage_data_in_history\n    staging_interface.handle_jobs()\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 212, in handle_jobs\n    self.galaxy_interactor.wait_for_job(job_response[\"id\"], job_response[\"history_id\"], self.maxseconds)\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 399, in wait_for_job\n    self.wait_for(lambda: self.__job_ready(job_id, history_id), maxseconds=maxseconds)\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 403, in wait_for\n    wait_on(func, what, walltime_exceeded)\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/wait.py\", line 38, in wait_on\n    value = function()\n            ^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 399, in \u003clambda\u003e\n    self.wait_for(lambda: self.__job_ready(job_id, history_id), maxseconds=maxseconds)\n                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 749, in __job_ready\n    return self._state_ready(job_id, error_msg=\"Job in error state.\")\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 841, in _state_ready\n    raise Exception(\nException: Job in error state.. tool_id: __DATA_FETCH__, exit_code: None, stderr: .\n", "status": "error", "test_index": 4, "time_seconds": 10.913183450698853, "tool_id": "flash", "tool_version": "1.2.11.4"}
            ]]></error>
        
    </testcase>
    
    <testcase classname="ivar_filtervariants (Test #1)" name="0" time="43.90859007835388">
        
            
            <system-out><![CDATA[
            Header format of ./var_0.tsv did not match! Please use files generated using "ivar variants" command.
            ]]></system-out>
            <system-err><![CDATA[
            
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="medaka_consensus (Test #1)" name="0" time="72.42776894569397">
        
            
            <system-out><![CDATA[
            [01:18:26 - Predict] Reducing threads to 2, anymore is a waste.[01:18:26 - Predict] It looks like you are running medaka without a GPU and attempted to set a high number of threads. We have scaled this down to an optimal number. If you wish to improve performance please see https://nanoporetech.github.io/medaka/installation.html#improving-parallelism.[01:18:26 - Predict] Setting tensorflow inter/intra-op threads to 2/1.[01:18:26 - Predict] Processing region(s): ref:0-30[01:18:26 - Predict] Using model: /usr/local/lib/python3.8/site-packages/medaka/data/r941_min_high_g360_model.hdf5.[01:18:26 - DataStre] Writing sample registry.[01:18:26 - Predict] Processing 1 long region(s) with batching.[01:18:26 - MdlStore] filepath /usr/local/lib/python3.8/site-packages/medaka/data/r941_min_high_g360_model.hdf52025-08-14 01:18:26.478211: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE4.1 SSE4.2 AVX AVX2 FMATo enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.[01:18:27 - BAMFile] Creating pool of 16 BAM file sets.[01:18:27 - DLoader] Sample-0: started[01:18:27 - Sampler] Initializing sampler for consensus of region ref:0-30.[01:18:27 - DLoader] Sample-1: started[01:18:27 - DLoader] Sample-1: finished[01:18:27 - DLoader] Initialised. Batch size:100. Workers:2. Cache:800[01:18:27 - PWorker] Running inference for 0.0M draft bases.[01:18:27 - Feature] Pileup counts do not span requested region, requested ref:0-30, received 0-9.[01:18:27 - Feature] Processed ref:0.0-9.0 (median depth 1.0)[01:18:27 - Feature] Pileup counts do not span requested region, requested ref:0-30, received 14-29.[01:18:27 - Feature] Processed ref:14.0-29.0 (median depth 1.0)[01:18:27 - Sampler] Took 0.06s to make features.[01:18:27 - Sampler] Region ref:0.0-9.0 (10 positions) is smaller than inference chunk length 10000, quarantining.[01:18:27 - Sampler] Region ref:14.0-29.0 (16 positions) is smaller than inference chunk length 10000, quarantining.[01:18:27 - DLoader] Sample-0: finished[01:18:27 - DLoader] Batches ready: 0. Samples ready: 0 (0.0 batches)[01:18:27 - DataStre] Writing sample registry.[01:18:27 - PWorker] Processed 0 batches[01:18:27 - PWorker] All done, 2 remainder regions.[01:18:27 - Predict] Processing 2 short region(s).[01:18:27 - MdlStore] filepath /usr/local/lib/python3.8/site-packages/medaka/data/r941_min_high_g360_model.hdf5[01:18:27 - DLoader] Sample-0: started[01:18:27 - Sampler] Initializing sampler for consensus of region ref:0-10.[01:18:27 - DLoader] Sample-1: started[01:18:27 - Sampler] Initializing sampler for consensus of region ref:14-30.[01:18:27 - Feature] Processed ref:14.0-29.0 (median depth 1.0)[01:18:27 - Sampler] Took 0.01s to make features.[01:18:27 - Sampler] Pileup for ref:14.0-29.0 is of width 16[01:18:27 - DLoader] Initialised. Batch size:1. Workers:2. Cache:8[01:18:27 - PWorker] Running inference for 0.0M draft bases.[01:18:27 - Feature] Processed ref:0.0-9.0 (median depth 1.0)[01:18:27 - Sampler] Took 0.02s to make features.[01:18:27 - Sampler] Pileup for ref:0.0-9.0 is of width 10[01:18:27 - DLoader] Sample-1: finished[01:18:27 - DLoader] Sample-0: finished[01:18:27 - DLoader] Batches ready: 0. Samples ready: 1 (1.0 batches)[01:18:27 - DataStre] Loaded sample register.[01:18:27 - DataStre] Adding ref:14.0-29.0 to sample registry[01:18:27 - DLoader] Batches ready: 1. Samples ready: 0 (0.0 batches)[01:18:27 - DataStre] Adding ref:0.0-9.0 to sample registry[01:18:27 - DLoader] Batches ready: 0. Samples ready: 0 (0.0 batches)[01:18:27 - DataStre] Writing sample registry.[01:18:27 - PWorker] Processed 2 batches[01:18:27 - PWorker] All done, 0 remainder regions.[01:18:27 - Predict] Finished processing all regions.[01:18:27 - BAMFile] Closing BAM file set.[01:18:27 - BAMFile] Closing BAM file set.[01:18:27 - BAMFile] Closing BAM file set.[01:18:27 - BAMFile] Closing BAM file set.[01:18:27 - BAMFile] Closing BAM file set.[01:18:27 - BAMFile] Closing BAM file set.[01:18:27 - BAMFile] Closing BAM file set.[01:18:27 - BAMFile] Closing BAM file set.[01:18:27 - BAMFile] Closing BAM file set.[01:18:27 - BAMFile] Closing BAM file set.[01:18:27 - BAMFile] Closing BAM file set.[01:18:27 - BAMFile] Closing BAM file set.[01:18:27 - BAMFile] Closing BAM file set.[01:18:27 - BAMFile] Closing BAM file set.[01:18:27 - BAMFile] Closing BAM file set.[01:18:27 - BAMFile] Closing BAM file set.
            ]]></system-out>
            <system-err><![CDATA[
            
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="medaka_consensus (Test #2)" name="1" time="10.618175506591797">
        
            <error type="error" message="Input staging problem: Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 1436, in verify_tool
    stage_data_in_history(
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 175, in stage_data_in_history
    staging_interface.handle_jobs()
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 212, in handle_jobs
    self.galaxy_interactor.wait_for_job(job_response["id"], job_response["history_id"], self.maxseconds)
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 399, in wait_for_job
    self.wait_for(lambda: self.__job_ready(job_id, history_id), maxseconds=maxseconds)
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 403, in wait_for
    wait_on(func, what, walltime_exceeded)
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/wait.py", line 38, in wait_on
    value = function()
            ^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 399, in <lambda>
    self.wait_for(lambda: self.__job_ready(job_id, history_id), maxseconds=maxseconds)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 749, in __job_ready
    return self._state_ready(job_id, error_msg="Job in error state.")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 841, in _state_ready
    raise Exception(
Exception: Job in error state.. tool_id: __DATA_FETCH__, exit_code: None, stderr: .
"><![CDATA[
                { "execution_problem": "Input staging problem: Traceback (most recent call last):\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 1436, in verify_tool\n    stage_data_in_history(\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 175, in stage_data_in_history\n    staging_interface.handle_jobs()\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 212, in handle_jobs\n    self.galaxy_interactor.wait_for_job(job_response[\"id\"], job_response[\"history_id\"], self.maxseconds)\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 399, in wait_for_job\n    self.wait_for(lambda: self.__job_ready(job_id, history_id), maxseconds=maxseconds)\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 403, in wait_for\n    wait_on(func, what, walltime_exceeded)\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/wait.py\", line 38, in wait_on\n    value = function()\n            ^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 399, in \u003clambda\u003e\n    self.wait_for(lambda: self.__job_ready(job_id, history_id), maxseconds=maxseconds)\n                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 749, in __job_ready\n    return self._state_ready(job_id, error_msg=\"Job in error state.\")\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 841, in _state_ready\n    raise Exception(\nException: Job in error state.. tool_id: __DATA_FETCH__, exit_code: None, stderr: .\n", "status": "error", "test_index": 1, "time_seconds": 10.618175506591797, "tool_id": "medaka_consensus", "tool_version": "1.7.2+galaxy0"}
            ]]></error>
        
    </testcase>
    
    <testcase classname="poretools_nucdist (Test #1)" name="0" time="101.91679215431213">
        
            
            <system-out><![CDATA[
            
            ]]></system-out>
            <system-err><![CDATA[
            
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="poretools_nucdist (Test #2)" name="1" time="11.856940269470215">
        
            <error type="error" message="Input staging problem: Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 1436, in verify_tool
    stage_data_in_history(
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 175, in stage_data_in_history
    staging_interface.handle_jobs()
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 212, in handle_jobs
    self.galaxy_interactor.wait_for_job(job_response["id"], job_response["history_id"], self.maxseconds)
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 399, in wait_for_job
    self.wait_for(lambda: self.__job_ready(job_id, history_id), maxseconds=maxseconds)
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 403, in wait_for
    wait_on(func, what, walltime_exceeded)
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/wait.py", line 38, in wait_on
    value = function()
            ^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 399, in <lambda>
    self.wait_for(lambda: self.__job_ready(job_id, history_id), maxseconds=maxseconds)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 749, in __job_ready
    return self._state_ready(job_id, error_msg="Job in error state.")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 841, in _state_ready
    raise Exception(
Exception: Job in error state.. tool_id: __DATA_FETCH__, exit_code: None, stderr: .
"><![CDATA[
                { "execution_problem": "Input staging problem: Traceback (most recent call last):\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 1436, in verify_tool\n    stage_data_in_history(\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 175, in stage_data_in_history\n    staging_interface.handle_jobs()\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 212, in handle_jobs\n    self.galaxy_interactor.wait_for_job(job_response[\"id\"], job_response[\"history_id\"], self.maxseconds)\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 399, in wait_for_job\n    self.wait_for(lambda: self.__job_ready(job_id, history_id), maxseconds=maxseconds)\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 403, in wait_for\n    wait_on(func, what, walltime_exceeded)\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/wait.py\", line 38, in wait_on\n    value = function()\n            ^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 399, in \u003clambda\u003e\n    self.wait_for(lambda: self.__job_ready(job_id, history_id), maxseconds=maxseconds)\n                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 749, in __job_ready\n    return self._state_ready(job_id, error_msg=\"Job in error state.\")\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 841, in _state_ready\n    raise Exception(\nException: Job in error state.. tool_id: __DATA_FETCH__, exit_code: None, stderr: .\n", "status": "error", "test_index": 1, "time_seconds": 11.856940269470215, "tool_id": "poretools_nucdist", "tool_version": "0.6.1a1.0"}
            ]]></error>
        
    </testcase>
    
    <testcase classname="qualimap_multi_bamqc (Test #1)" name="0" time="30.004079580307007">
        
            <error type="error" message="Input staging problem: Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 1436, in verify_tool
    stage_data_in_history(
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 175, in stage_data_in_history
    staging_interface.handle_jobs()
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 212, in handle_jobs
    self.galaxy_interactor.wait_for_job(job_response["id"], job_response["history_id"], self.maxseconds)
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 399, in wait_for_job
    self.wait_for(lambda: self.__job_ready(job_id, history_id), maxseconds=maxseconds)
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 403, in wait_for
    wait_on(func, what, walltime_exceeded)
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/wait.py", line 38, in wait_on
    value = function()
            ^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 399, in <lambda>
    self.wait_for(lambda: self.__job_ready(job_id, history_id), maxseconds=maxseconds)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 749, in __job_ready
    return self._state_ready(job_id, error_msg="Job in error state.")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 841, in _state_ready
    raise Exception(
Exception: Job in error state.. tool_id: __DATA_FETCH__, exit_code: None, stderr: .
"><![CDATA[
                { "execution_problem": "Input staging problem: Traceback (most recent call last):\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 1436, in verify_tool\n    stage_data_in_history(\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 175, in stage_data_in_history\n    staging_interface.handle_jobs()\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 212, in handle_jobs\n    self.galaxy_interactor.wait_for_job(job_response[\"id\"], job_response[\"history_id\"], self.maxseconds)\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 399, in wait_for_job\n    self.wait_for(lambda: self.__job_ready(job_id, history_id), maxseconds=maxseconds)\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 403, in wait_for\n    wait_on(func, what, walltime_exceeded)\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/wait.py\", line 38, in wait_on\n    value = function()\n            ^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 399, in \u003clambda\u003e\n    self.wait_for(lambda: self.__job_ready(job_id, history_id), maxseconds=maxseconds)\n                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 749, in __job_ready\n    return self._state_ready(job_id, error_msg=\"Job in error state.\")\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 841, in _state_ready\n    raise Exception(\nException: Job in error state.. tool_id: __DATA_FETCH__, exit_code: None, stderr: .\n", "status": "error", "test_index": 0, "time_seconds": 30.004079580307007, "tool_id": "qualimap_multi_bamqc", "tool_version": "2.3+galaxy0"}
            ]]></error>
        
    </testcase>
    
    <testcase classname="racon (Test #1)" name="0" time="47.11437225341797">
        
            
                <error type="error" message="Tool exit code: 132"><![CDATA[
                    { "inputs": {  "corrected_reads": {   "id": "3d602f247695b9d8",   "src": "hda"  },  "error_threshold": "0.2",  "fragment_correction": true,  "include_unpolished": true,  "overlaps": {   "id": "6ed9225cdbef38e3",   "src": "hda"  },  "reads": {   "id": "ade3c2d9e492fb21",   "src": "hda"  },  "window_length": "800" }, "job": {  "command_line": "ln -s \u0027/galaxy/server/database/objects/0/8/1/dataset_081bfa00-498b-4e14-b28b-a7f763564563.dat\u0027 reads.fasta \u0026\u0026 ln -s \u0027/galaxy/server/database/objects/4/0/0/dataset_400f6cdc-8929-411a-94ae-bfa0df61e6fc.dat\u0027 overlaps.sam \u0026\u0026  ln -s \u0027/galaxy/server/database/objects/d/6/c/dataset_d6c84e41-584c-4a43-8902-41187a536e76.dat\u0027 corrected_reads.fasta \u0026\u0026  racon reads.fasta overlaps.sam corrected_reads.fasta -t ${GALAXY_SLOTS:-4} -u -f -w 800 -q 10.0 -e 0.2  -m 3 -x -5 -g -4 \u003e racon_polished_consensus.fa",  "command_version": "1.5.0",  "copied_from_job_id": null,  "create_time": "2025-08-14T01:22:17.058121",  "dependencies": [],  "exit_code": 132,  "external_id": "gxy-b8bgc",  "galaxy_version": "24.1",  "handler": null,  "history_id": "56a0493b6f9a16b3",  "id": "06392917d4c55eb8",  "inputs": {   "corrected_reads": {    "id": "3d602f247695b9d8",    "src": "hda",    "uuid": "d6c84e41-584c-4a43-8902-41187a536e76"   },   "overlaps": {    "id": "6ed9225cdbef38e3",    "src": "hda",    "uuid": "400f6cdc-8929-411a-94ae-bfa0df61e6fc"   },   "reads": {    "id": "ade3c2d9e492fb21",    "src": "hda",    "uuid": "081bfa00-498b-4e14-b28b-a7f763564563"   }  },  "job_messages": [   {    "code_desc": "",    "desc": "Fatal error: Exit code 132 ()",    "error_level": 3,    "exit_code": 132,    "type": "exit_code"   }  ],  "job_metrics": [   {    "name": "runtime_seconds",    "plugin": "core",    "raw_value": "0E-7",    "title": "Job Runtime (Wall Clock)",    "value": "0 seconds"   },   {    "name": "end_epoch",    "plugin": "core",    "raw_value": "1755134547.0000000",    "title": "Job End Time",    "value": "2025-08-14 01:22:27"   },   {    "name": "start_epoch",    "plugin": "core",    "raw_value": "1755134547.0000000",    "title": "Job Start Time",    "value": "2025-08-14 01:22:27"   },   {    "name": "galaxy_memory_mb",    "plugin": "core",    "raw_value": "38654.0000000",    "title": "Memory Allocated (MB)",    "value": "38654"   },   {    "name": "galaxy_slots",    "plugin": "core",    "raw_value": "8.0000000",    "title": "Cores Allocated",    "value": "8"   }  ],  "job_runner_name": null,  "job_stderr": "",  "job_stdout": "",  "model_class": "Job",  "output_collections": {},  "outputs": {   "consensus": {    "id": "628de686f632b57f",    "src": "hda",    "uuid": "f1267a60-5573-490d-88a3-b6a06541e7e5"   }  },  "params": {   "__input_ext": "\"input\"",   "chromInfo": "\"/cvmfs/data.galaxyproject.org/managed/len/ucsc/?.len\"",   "dbkey": "\"?\"",   "error_threshold": "\"0.2\"",   "fragment_correction": "true",   "gap": "\"-4\"",   "include_unpolished": "true",   "match": "\"3\"",   "mismatch": "\"-5\"",   "no_trimming": "false",   "quality_threshold": "\"10.0\"",   "window_length": "\"800\""  },  "state": "error",  "stderr": "/galaxy/server/database/jobs_directory/000/92/tool_script.sh: line 24:    27 Illegal instruction     (core dumped) racon reads.fasta overlaps.sam corrected_reads.fasta -t ${GALAXY_SLOTS:-4} -u -f -w 800 -q 10.0 -e 0.2 -m 3 -x -5 -g -4 \u003e racon_polished_consensus.fa\n",  "stdout": "",  "tool_id": "toolshed.g2.bx.psu.edu/repos/bgruening/racon/racon/1.5.0+galaxy1",  "tool_stderr": "/galaxy/server/database/jobs_directory/000/92/tool_script.sh: line 24:    27 Illegal instruction     (core dumped) racon reads.fasta overlaps.sam corrected_reads.fasta -t ${GALAXY_SLOTS:-4} -u -f -w 800 -q 10.0 -e 0.2 -m 3 -x -5 -g -4 \u003e racon_polished_consensus.fa\n",  "tool_stdout": "",  "update_time": "2025-08-14T01:22:39.395435",  "user_email": "tests@fake.org" }, "output_problems": [  "Job in error state.. tool_id: toolshed.g2.bx.psu.edu/repos/bgruening/racon/racon/1.5.0+galaxy1, exit_code: 132, stderr: /galaxy/server/database/jobs_directory/000/92/tool_script.sh: line 24:    27 Illegal instruction     (core dumped) racon reads.fasta overlaps.sam corrected_reads.fasta -t ${GALAXY_SLOTS:-4} -u -f -w 800 -q 10.0 -e 0.2 -m 3 -x -5 -g -4 \u003e racon_polished_consensus.fa\n.",  "Job in error state.. tool_id: toolshed.g2.bx.psu.edu/repos/bgruening/racon/racon/1.5.0+galaxy1, exit_code: 132, stderr: /galaxy/server/database/jobs_directory/000/92/tool_script.sh: line 24:    27 Illegal instruction     (core dumped) racon reads.fasta overlaps.sam corrected_reads.fasta -t ${GALAXY_SLOTS:-4} -u -f -w 800 -q 10.0 -e 0.2 -m 3 -x -5 -g -4 \u003e racon_polished_consensus.fa\n." ], "status": "failure", "test_index": 0, "time_seconds": 47.11437225341797, "tool_id": "racon", "tool_version": "1.5.0+galaxy1"}
                ]]></error>
            
            <system-out><![CDATA[
            
            ]]></system-out>
            <system-err><![CDATA[
            /galaxy/server/database/jobs_directory/000/92/tool_script.sh: line 24:    27 Illegal instruction     (core dumped) racon reads.fasta overlaps.sam corrected_reads.fasta -t ${GALAXY_SLOTS:-4} -u -f -w 800 -q 10.0 -e 0.2 -m 3 -x -5 -g -4 > racon_polished_consensus.fa
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="racon (Test #2)" name="1" time="35.91128134727478">
        
            
                <error type="error" message="Tool exit code: 132"><![CDATA[
                    { "inputs": {  "corrected_reads": {   "id": "7a28e39e2a585487",   "src": "hda"  },  "overlaps": {   "id": "4b4566af1491fa57",   "src": "hda"  },  "reads": {   "id": "ef8004fcccecc48e",   "src": "hda"  } }, "job": {  "command_line": "ln -s \u0027/galaxy/server/database/objects/b/a/f/dataset_baf3a44f-5bc2-4718-bd64-df947749d356.dat\u0027 reads.fasta \u0026\u0026 ln -s \u0027/galaxy/server/database/objects/3/3/c/dataset_33c61357-1455-499f-b387-1e3a44557391.dat\u0027 overlaps.paf \u0026\u0026  ln -s \u0027/galaxy/server/database/objects/5/0/0/dataset_50009e78-3620-498f-be71-93d2cc6d0276.dat\u0027 corrected_reads.fasta \u0026\u0026  racon reads.fasta overlaps.paf corrected_reads.fasta -t ${GALAXY_SLOTS:-4}   -w 500 -q 10.0 -e 0.3  -m 3 -x -5 -g -4 \u003e racon_polished_consensus.fa",  "command_version": "1.5.0",  "copied_from_job_id": null,  "create_time": "2025-08-14T01:23:03.801717",  "dependencies": [],  "exit_code": 132,  "external_id": "gxy-shf62",  "galaxy_version": "24.1",  "handler": null,  "history_id": "56a0493b6f9a16b3",  "id": "db2127a5d3ff662d",  "inputs": {   "corrected_reads": {    "id": "7a28e39e2a585487",    "src": "hda",    "uuid": "50009e78-3620-498f-be71-93d2cc6d0276"   },   "overlaps": {    "id": "4b4566af1491fa57",    "src": "hda",    "uuid": "33c61357-1455-499f-b387-1e3a44557391"   },   "reads": {    "id": "ef8004fcccecc48e",    "src": "hda",    "uuid": "baf3a44f-5bc2-4718-bd64-df947749d356"   }  },  "job_messages": [   {    "code_desc": "",    "desc": "Fatal error: Exit code 132 ()",    "error_level": 3,    "exit_code": 132,    "type": "exit_code"   }  ],  "job_metrics": [   {    "name": "runtime_seconds",    "plugin": "core",    "raw_value": "0E-7",    "title": "Job Runtime (Wall Clock)",    "value": "0 seconds"   },   {    "name": "end_epoch",    "plugin": "core",    "raw_value": "1755134585.0000000",    "title": "Job End Time",    "value": "2025-08-14 01:23:05"   },   {    "name": "start_epoch",    "plugin": "core",    "raw_value": "1755134585.0000000",    "title": "Job Start Time",    "value": "2025-08-14 01:23:05"   },   {    "name": "galaxy_memory_mb",    "plugin": "core",    "raw_value": "38654.0000000",    "title": "Memory Allocated (MB)",    "value": "38654"   },   {    "name": "galaxy_slots",    "plugin": "core",    "raw_value": "8.0000000",    "title": "Cores Allocated",    "value": "8"   }  ],  "job_runner_name": null,  "job_stderr": "",  "job_stdout": "",  "model_class": "Job",  "output_collections": {},  "outputs": {   "consensus": {    "id": "4236e224939529de",    "src": "hda",    "uuid": "1b831b13-bf0b-4c0c-a276-ee46cb5d5013"   }  },  "params": {   "__input_ext": "\"input\"",   "chromInfo": "\"/cvmfs/data.galaxyproject.org/managed/len/ucsc/?.len\"",   "dbkey": "\"?\"",   "error_threshold": "\"0.3\"",   "fragment_correction": "false",   "gap": "\"-4\"",   "include_unpolished": "false",   "match": "\"3\"",   "mismatch": "\"-5\"",   "no_trimming": "false",   "quality_threshold": "\"10.0\"",   "window_length": "\"500\""  },  "state": "error",  "stderr": "/galaxy/server/database/jobs_directory/000/96/tool_script.sh: line 24:    27 Illegal instruction     (core dumped) racon reads.fasta overlaps.paf corrected_reads.fasta -t ${GALAXY_SLOTS:-4} -w 500 -q 10.0 -e 0.3 -m 3 -x -5 -g -4 \u003e racon_polished_consensus.fa\n",  "stdout": "",  "tool_id": "toolshed.g2.bx.psu.edu/repos/bgruening/racon/racon/1.5.0+galaxy1",  "tool_stderr": "/galaxy/server/database/jobs_directory/000/96/tool_script.sh: line 24:    27 Illegal instruction     (core dumped) racon reads.fasta overlaps.paf corrected_reads.fasta -t ${GALAXY_SLOTS:-4} -w 500 -q 10.0 -e 0.3 -m 3 -x -5 -g -4 \u003e racon_polished_consensus.fa\n",  "tool_stdout": "",  "update_time": "2025-08-14T01:23:15.461080",  "user_email": "tests@fake.org" }, "output_problems": [  "Job in error state.. tool_id: toolshed.g2.bx.psu.edu/repos/bgruening/racon/racon/1.5.0+galaxy1, exit_code: 132, stderr: /galaxy/server/database/jobs_directory/000/96/tool_script.sh: line 24:    27 Illegal instruction     (core dumped) racon reads.fasta overlaps.paf corrected_reads.fasta -t ${GALAXY_SLOTS:-4} -w 500 -q 10.0 -e 0.3 -m 3 -x -5 -g -4 \u003e racon_polished_consensus.fa\n.",  "Job in error state.. tool_id: toolshed.g2.bx.psu.edu/repos/bgruening/racon/racon/1.5.0+galaxy1, exit_code: 132, stderr: /galaxy/server/database/jobs_directory/000/96/tool_script.sh: line 24:    27 Illegal instruction     (core dumped) racon reads.fasta overlaps.paf corrected_reads.fasta -t ${GALAXY_SLOTS:-4} -w 500 -q 10.0 -e 0.3 -m 3 -x -5 -g -4 \u003e racon_polished_consensus.fa\n." ], "status": "failure", "test_index": 1, "time_seconds": 35.91128134727478, "tool_id": "racon", "tool_version": "1.5.0+galaxy1"}
                ]]></error>
            
            <system-out><![CDATA[
            
            ]]></system-out>
            <system-err><![CDATA[
            /galaxy/server/database/jobs_directory/000/96/tool_script.sh: line 24:    27 Illegal instruction     (core dumped) racon reads.fasta overlaps.paf corrected_reads.fasta -t ${GALAXY_SLOTS:-4} -w 500 -q 10.0 -e 0.3 -m 3 -x -5 -g -4 > racon_polished_consensus.fa
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="racon (Test #3)" name="2" time="11.22808575630188">
        
            <error type="error" message="Input staging problem: Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 1436, in verify_tool
    stage_data_in_history(
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 175, in stage_data_in_history
    staging_interface.handle_jobs()
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 212, in handle_jobs
    self.galaxy_interactor.wait_for_job(job_response["id"], job_response["history_id"], self.maxseconds)
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 399, in wait_for_job
    self.wait_for(lambda: self.__job_ready(job_id, history_id), maxseconds=maxseconds)
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 403, in wait_for
    wait_on(func, what, walltime_exceeded)
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/wait.py", line 38, in wait_on
    value = function()
            ^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 399, in <lambda>
    self.wait_for(lambda: self.__job_ready(job_id, history_id), maxseconds=maxseconds)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 749, in __job_ready
    return self._state_ready(job_id, error_msg="Job in error state.")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 841, in _state_ready
    raise Exception(
Exception: Job in error state.. tool_id: __DATA_FETCH__, exit_code: None, stderr: .
"><![CDATA[
                { "execution_problem": "Input staging problem: Traceback (most recent call last):\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 1436, in verify_tool\n    stage_data_in_history(\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 175, in stage_data_in_history\n    staging_interface.handle_jobs()\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 212, in handle_jobs\n    self.galaxy_interactor.wait_for_job(job_response[\"id\"], job_response[\"history_id\"], self.maxseconds)\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 399, in wait_for_job\n    self.wait_for(lambda: self.__job_ready(job_id, history_id), maxseconds=maxseconds)\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 403, in wait_for\n    wait_on(func, what, walltime_exceeded)\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/wait.py\", line 38, in wait_on\n    value = function()\n            ^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 399, in \u003clambda\u003e\n    self.wait_for(lambda: self.__job_ready(job_id, history_id), maxseconds=maxseconds)\n                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 749, in __job_ready\n    return self._state_ready(job_id, error_msg=\"Job in error state.\")\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 841, in _state_ready\n    raise Exception(\nException: Job in error state.. tool_id: __DATA_FETCH__, exit_code: None, stderr: .\n", "status": "error", "test_index": 2, "time_seconds": 11.22808575630188, "tool_id": "racon", "tool_version": "1.5.0+galaxy1"}
            ]]></error>
        
    </testcase>
    
    <testcase classname="samtools_sort (Test #1)" name="0" time="45.460203647613525">
        
            
            <system-out><![CDATA[
            
            ]]></system-out>
            <system-err><![CDATA[
            
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="samtools_sort (Test #2)" name="1" time="23.954445600509644">
        
            
                <error type="error" message="Tool exit code: None"><![CDATA[
                    { "inputs": {  "input1": {   "id": "fcf0a67e7d6d43b1",   "src": "hda"  },  "prim_key_cond|prim_key_select": "-n" }, "job": {  "command_line": "addthreads=${GALAXY_SLOTS:-1} \u0026\u0026 (( addthreads-- )) \u0026\u0026   addmemory=${GALAXY_MEMORY_MB_PER_SLOT:-768} \u0026\u0026 ((addmemory=addmemory*75/100)) \u0026\u0026  samtools sort -@ $addthreads -m $addmemory\"M\" -n  -O bam -T \"${TMPDIR:-.}\" \u0027/galaxy/server/database/objects/d/6/8/dataset_d6890ebe-07c7-48d4-a400-9fd0a402eea6.dat\u0027 \u003e \u0027/galaxy/server/database/objects/8/f/7/dataset_8f7c979f-2fdb-49d0-90d6-8445f7e4a7d5.dat\u0027",  "command_version": null,  "copied_from_job_id": null,  "create_time": "2025-08-14T01:07:50.238444",  "dependencies": [],  "exit_code": null,  "external_id": "gxy-rph7t",  "galaxy_version": "24.1",  "handler": null,  "history_id": "56a0493b6f9a16b3",  "id": "2a8d02c64ffbf7a9",  "inputs": {   "input1": {    "id": "fcf0a67e7d6d43b1",    "src": "hda",    "uuid": "d6890ebe-07c7-48d4-a400-9fd0a402eea6"   }  },  "job_messages": null,  "job_metrics": [],  "job_runner_name": null,  "job_stderr": null,  "job_stdout": null,  "model_class": "Job",  "output_collections": {},  "outputs": {   "output1": {    "id": "5267b65c40b7d09a",    "src": "hda",    "uuid": "8f7c979f-2fdb-49d0-90d6-8445f7e4a7d5"   }  },  "params": {   "__input_ext": "\"input\"",   "chromInfo": "\"/cvmfs/data.galaxyproject.org/managed/len/ucsc/?.len\"",   "dbkey": "\"?\"",   "minhash": "false",   "prim_key_cond": "{\"__current_case__\": 1, \"prim_key_select\": \"-n\"}"  },  "state": "error",  "stderr": "",  "stdout": "",  "tool_id": "toolshed.g2.bx.psu.edu/repos/devteam/samtools_sort/samtools_sort/2.0.7",  "tool_stderr": "",  "tool_stdout": "",  "update_time": "2025-08-14T01:07:55.200018",  "user_email": "tests@fake.org" }, "output_problems": [  "Job in error state.. tool_id: toolshed.g2.bx.psu.edu/repos/devteam/samtools_sort/samtools_sort/2.0.7, exit_code: None, stderr: .",  "Job in error state.. tool_id: toolshed.g2.bx.psu.edu/repos/devteam/samtools_sort/samtools_sort/2.0.7, exit_code: None, stderr: ." ], "status": "failure", "test_index": 1, "time_seconds": 23.954445600509644, "tool_id": "samtools_sort", "tool_version": "2.0.7"}
                ]]></error>
            
            <system-out><![CDATA[
            
            ]]></system-out>
            <system-err><![CDATA[
            
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="samtools_sort (Test #3)" name="2" time="31.89745330810547">
        
            
            <system-out><![CDATA[
            
            ]]></system-out>
            <system-err><![CDATA[
            
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="samtools_sort (Test #4)" name="3" time="23.89954113960266">
        
            
                <error type="error" message="Tool exit code: None"><![CDATA[
                    { "inputs": {  "input1": {   "id": "f3c6ff1e955b15db",   "src": "hda"  },  "prim_key_cond|prim_key_select": "-t",  "prim_key_cond|sec_key_select": "-n",  "prim_key_cond|tag": "RG" }, "job": {  "command_line": "addthreads=${GALAXY_SLOTS:-1} \u0026\u0026 (( addthreads-- )) \u0026\u0026   addmemory=${GALAXY_MEMORY_MB_PER_SLOT:-768} \u0026\u0026 ((addmemory=addmemory*75/100)) \u0026\u0026  samtools sort -@ $addthreads -m $addmemory\"M\" -t RG -n  -O bam -T \"${TMPDIR:-.}\" \u0027/galaxy/server/database/objects/b/e/d/dataset_bed6b6c8-4eaf-4269-92b7-e440449ab213.dat\u0027 \u003e \u0027/galaxy/server/database/objects/7/6/7/dataset_76759341-2179-4b99-ba6e-431a008fd23b.dat\u0027",  "command_version": null,  "copied_from_job_id": null,  "create_time": "2025-08-14T01:08:46.316883",  "dependencies": [],  "exit_code": null,  "external_id": "gxy-b24hd",  "galaxy_version": "24.1",  "handler": null,  "history_id": "56a0493b6f9a16b3",  "id": "00a117eef5aff8e4",  "inputs": {   "input1": {    "id": "f3c6ff1e955b15db",    "src": "hda",    "uuid": "bed6b6c8-4eaf-4269-92b7-e440449ab213"   }  },  "job_messages": null,  "job_metrics": [],  "job_runner_name": null,  "job_stderr": null,  "job_stdout": null,  "model_class": "Job",  "output_collections": {},  "outputs": {   "output1": {    "id": "376ae74180feb375",    "src": "hda",    "uuid": "76759341-2179-4b99-ba6e-431a008fd23b"   }  },  "params": {   "__input_ext": "\"input\"",   "chromInfo": "\"/cvmfs/data.galaxyproject.org/managed/len/ucsc/?.len\"",   "dbkey": "\"?\"",   "minhash": "false",   "prim_key_cond": "{\"__current_case__\": 2, \"prim_key_select\": \"-t\", \"sec_key_select\": \"-n\", \"tag\": \"RG\"}"  },  "state": "error",  "stderr": "",  "stdout": "",  "tool_id": "toolshed.g2.bx.psu.edu/repos/devteam/samtools_sort/samtools_sort/2.0.7",  "tool_stderr": "",  "tool_stdout": "",  "update_time": "2025-08-14T01:08:51.330054",  "user_email": "tests@fake.org" }, "output_problems": [  "Job in error state.. tool_id: toolshed.g2.bx.psu.edu/repos/devteam/samtools_sort/samtools_sort/2.0.7, exit_code: None, stderr: .",  "Job in error state.. tool_id: toolshed.g2.bx.psu.edu/repos/devteam/samtools_sort/samtools_sort/2.0.7, exit_code: None, stderr: ." ], "status": "failure", "test_index": 3, "time_seconds": 23.89954113960266, "tool_id": "samtools_sort", "tool_version": "2.0.7"}
                ]]></error>
            
            <system-out><![CDATA[
            
            ]]></system-out>
            <system-err><![CDATA[
            
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="samtools_sort (Test #5)" name="4" time="33.41172933578491">
        
            
            <system-out><![CDATA[
            
            ]]></system-out>
            <system-err><![CDATA[
            
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="samtools_sort (Test #6)" name="5" time="34.460248947143555">
        
            
            <system-out><![CDATA[
            
            ]]></system-out>
            <system-err><![CDATA[
            
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="samtools_sort (Test #7)" name="6" time="34.05838108062744">
        
            
            <system-out><![CDATA[
            
            ]]></system-out>
            <system-err><![CDATA[
            
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="samtools_sort (Test #8)" name="7" time="33.30946326255798">
        
            
            <system-out><![CDATA[
            
            ]]></system-out>
            <system-err><![CDATA[
            
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="samtools_sort (Test #9)" name="8" time="13.094796180725098">
        
            <error type="error" message="Input staging problem: Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 1436, in verify_tool
    stage_data_in_history(
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 175, in stage_data_in_history
    staging_interface.handle_jobs()
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 212, in handle_jobs
    self.galaxy_interactor.wait_for_job(job_response["id"], job_response["history_id"], self.maxseconds)
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 399, in wait_for_job
    self.wait_for(lambda: self.__job_ready(job_id, history_id), maxseconds=maxseconds)
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 403, in wait_for
    wait_on(func, what, walltime_exceeded)
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/wait.py", line 38, in wait_on
    value = function()
            ^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 399, in <lambda>
    self.wait_for(lambda: self.__job_ready(job_id, history_id), maxseconds=maxseconds)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 749, in __job_ready
    return self._state_ready(job_id, error_msg="Job in error state.")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 841, in _state_ready
    raise Exception(
Exception: Job in error state.. tool_id: __DATA_FETCH__, exit_code: None, stderr: .
"><![CDATA[
                { "execution_problem": "Input staging problem: Traceback (most recent call last):\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 1436, in verify_tool\n    stage_data_in_history(\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 175, in stage_data_in_history\n    staging_interface.handle_jobs()\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 212, in handle_jobs\n    self.galaxy_interactor.wait_for_job(job_response[\"id\"], job_response[\"history_id\"], self.maxseconds)\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 399, in wait_for_job\n    self.wait_for(lambda: self.__job_ready(job_id, history_id), maxseconds=maxseconds)\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 403, in wait_for\n    wait_on(func, what, walltime_exceeded)\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/wait.py\", line 38, in wait_on\n    value = function()\n            ^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 399, in \u003clambda\u003e\n    self.wait_for(lambda: self.__job_ready(job_id, history_id), maxseconds=maxseconds)\n                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 749, in __job_ready\n    return self._state_ready(job_id, error_msg=\"Job in error state.\")\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 841, in _state_ready\n    raise Exception(\nException: Job in error state.. tool_id: __DATA_FETCH__, exit_code: None, stderr: .\n", "status": "error", "test_index": 8, "time_seconds": 13.094796180725098, "tool_id": "samtools_sort", "tool_version": "2.0.7"}
            ]]></error>
        
    </testcase>
    
    <testcase classname="vcfallelicprimitives (Test #1)" name="0" time="42.3784441947937">
        
            
            <system-out><![CDATA[
            
            ]]></system-out>
            <system-err><![CDATA[
            
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="vcfprimers (Test #1)" name="0" time="33.19832968711853">
        
            
            <system-out><![CDATA[
            
            ]]></system-out>
            <system-err><![CDATA[
            index file localref.fa.fai not found, generating...
            ]]></system-err>
        
    </testcase>
    
</testsuite>