<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="Results (powered by Planemo)"
           tests="44"
           errors="8"
           failures="1"
           skip="0">
    
    <testcase classname="bcftools_norm (Test #1)" name="0" time="11.631782531738281">
        
            <error type="error" message="Input staging problem: Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 1434, in verify_tool
    stage_data_in_history(
  File "/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 175, in stage_data_in_history
    staging_interface.handle_jobs()
  File "/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 212, in handle_jobs
    self.galaxy_interactor.wait_for_job(job_response["id"], job_response["history_id"], self.maxseconds)
  File "/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 399, in wait_for_job
    self.wait_for(lambda: self.__job_ready(job_id, history_id), maxseconds=maxseconds)
  File "/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 403, in wait_for
    wait_on(func, what, walltime_exceeded)
  File "/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/wait.py", line 38, in wait_on
    value = function()
            ^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 399, in <lambda>
    self.wait_for(lambda: self.__job_ready(job_id, history_id), maxseconds=maxseconds)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 747, in __job_ready
    return self._state_ready(job_id, error_msg="Job in error state.")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 839, in _state_ready
    raise Exception(
Exception: Job in error state.. tool_id: __DATA_FETCH__, exit_code: None, stderr: .
"><![CDATA[
                { "execution_problem": "Input staging problem: Traceback (most recent call last):\n  File \"/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 1434, in verify_tool\n    stage_data_in_history(\n  File \"/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 175, in stage_data_in_history\n    staging_interface.handle_jobs()\n  File \"/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 212, in handle_jobs\n    self.galaxy_interactor.wait_for_job(job_response[\"id\"], job_response[\"history_id\"], self.maxseconds)\n  File \"/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 399, in wait_for_job\n    self.wait_for(lambda: self.__job_ready(job_id, history_id), maxseconds=maxseconds)\n  File \"/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 403, in wait_for\n    wait_on(func, what, walltime_exceeded)\n  File \"/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/wait.py\", line 38, in wait_on\n    value = function()\n            ^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 399, in \u003clambda\u003e\n    self.wait_for(lambda: self.__job_ready(job_id, history_id), maxseconds=maxseconds)\n                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 747, in __job_ready\n    return self._state_ready(job_id, error_msg=\"Job in error state.\")\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 839, in _state_ready\n    raise Exception(\nException: Job in error state.. tool_id: __DATA_FETCH__, exit_code: None, stderr: .\n", "status": "error", "test_index": 0, "time_seconds": 11.631782531738281, "tool_id": "bcftools_norm", "tool_version": "1.15.1+galaxy4"}
            ]]></error>
        
    </testcase>
    
    <testcase classname="bcftools_norm (Test #2)" name="1" time="">
        
            <error type="error" message=""><![CDATA[
                { "status": "skip", "test_index": 1, "tool_id": "bcftools_norm", "tool_version": "1.15.1+galaxy4"}
            ]]></error>
        
    </testcase>
    
    <testcase classname="bcftools_norm (Test #3)" name="2" time="42.362332820892334">
        
            
            <system-out><![CDATA[
            
            ]]></system-out>
            <system-err><![CDATA[
            Lines   total/split/realigned/skipped:19/7/0/0
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="bcftools_norm (Test #4)" name="3" time="32.53105592727661">
        
            
            <system-out><![CDATA[
            
            ]]></system-out>
            <system-err><![CDATA[
            Lines   total/split/realigned/skipped:19/7/19/0
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="bcftools_norm (Test #5)" name="4" time="33.20707702636719">
        
            
            <system-out><![CDATA[
            
            ]]></system-out>
            <system-err><![CDATA[
            Lines   total/split/realigned/skipped:26/0/0/0
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="bcftools_norm (Test #6)" name="5" time="11.240407943725586">
        
            <error type="error" message="Input staging problem: Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 1434, in verify_tool
    stage_data_in_history(
  File "/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 175, in stage_data_in_history
    staging_interface.handle_jobs()
  File "/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 212, in handle_jobs
    self.galaxy_interactor.wait_for_job(job_response["id"], job_response["history_id"], self.maxseconds)
  File "/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 399, in wait_for_job
    self.wait_for(lambda: self.__job_ready(job_id, history_id), maxseconds=maxseconds)
  File "/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 403, in wait_for
    wait_on(func, what, walltime_exceeded)
  File "/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/wait.py", line 38, in wait_on
    value = function()
            ^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 399, in <lambda>
    self.wait_for(lambda: self.__job_ready(job_id, history_id), maxseconds=maxseconds)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 747, in __job_ready
    return self._state_ready(job_id, error_msg="Job in error state.")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 839, in _state_ready
    raise Exception(
Exception: Job in error state.. tool_id: __DATA_FETCH__, exit_code: None, stderr: .
"><![CDATA[
                { "execution_problem": "Input staging problem: Traceback (most recent call last):\n  File \"/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 1434, in verify_tool\n    stage_data_in_history(\n  File \"/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 175, in stage_data_in_history\n    staging_interface.handle_jobs()\n  File \"/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 212, in handle_jobs\n    self.galaxy_interactor.wait_for_job(job_response[\"id\"], job_response[\"history_id\"], self.maxseconds)\n  File \"/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 399, in wait_for_job\n    self.wait_for(lambda: self.__job_ready(job_id, history_id), maxseconds=maxseconds)\n  File \"/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 403, in wait_for\n    wait_on(func, what, walltime_exceeded)\n  File \"/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/wait.py\", line 38, in wait_on\n    value = function()\n            ^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 399, in \u003clambda\u003e\n    self.wait_for(lambda: self.__job_ready(job_id, history_id), maxseconds=maxseconds)\n                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 747, in __job_ready\n    return self._state_ready(job_id, error_msg=\"Job in error state.\")\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 839, in _state_ready\n    raise Exception(\nException: Job in error state.. tool_id: __DATA_FETCH__, exit_code: None, stderr: .\n", "status": "error", "test_index": 5, "time_seconds": 11.240407943725586, "tool_id": "bcftools_norm", "tool_version": "1.15.1+galaxy4"}
            ]]></error>
        
    </testcase>
    
    <testcase classname="bcftools_norm (Test #7)" name="6" time="33.167661905288696">
        
            
            <system-out><![CDATA[
            
            ]]></system-out>
            <system-err><![CDATA[
            Lines   total/split/realigned/skipped:8/0/0/0REF/ALT total/modified/added:  8/5/3
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="bcftools_norm (Test #8)" name="7" time="32.968342542648315">
        
            
            <system-out><![CDATA[
            
            ]]></system-out>
            <system-err><![CDATA[
            Lines   total/split/realigned/skipped:39/20/3/0
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="bcftools_norm (Test #9)" name="8" time="">
        
            <error type="error" message=""><![CDATA[
                { "status": "skip", "test_index": 8, "tool_id": "bcftools_norm", "tool_version": "1.15.1+galaxy4"}
            ]]></error>
        
    </testcase>
    
    <testcase classname="bcftools_plugin_fill_tags (Test #1)" name="0" time="38.67140603065491">
        
            
            <system-out><![CDATA[
            
            ]]></system-out>
            <system-err><![CDATA[
            
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="bcftools_plugin_fill_tags (Test #2)" name="1" time="10.668724060058594">
        
            <error type="error" message="Input staging problem: Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 1434, in verify_tool
    stage_data_in_history(
  File "/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 175, in stage_data_in_history
    staging_interface.handle_jobs()
  File "/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 212, in handle_jobs
    self.galaxy_interactor.wait_for_job(job_response["id"], job_response["history_id"], self.maxseconds)
  File "/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 399, in wait_for_job
    self.wait_for(lambda: self.__job_ready(job_id, history_id), maxseconds=maxseconds)
  File "/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 403, in wait_for
    wait_on(func, what, walltime_exceeded)
  File "/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/wait.py", line 38, in wait_on
    value = function()
            ^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 399, in <lambda>
    self.wait_for(lambda: self.__job_ready(job_id, history_id), maxseconds=maxseconds)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 747, in __job_ready
    return self._state_ready(job_id, error_msg="Job in error state.")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 839, in _state_ready
    raise Exception(
Exception: Job in error state.. tool_id: __DATA_FETCH__, exit_code: None, stderr: .
"><![CDATA[
                { "execution_problem": "Input staging problem: Traceback (most recent call last):\n  File \"/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 1434, in verify_tool\n    stage_data_in_history(\n  File \"/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 175, in stage_data_in_history\n    staging_interface.handle_jobs()\n  File \"/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 212, in handle_jobs\n    self.galaxy_interactor.wait_for_job(job_response[\"id\"], job_response[\"history_id\"], self.maxseconds)\n  File \"/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 399, in wait_for_job\n    self.wait_for(lambda: self.__job_ready(job_id, history_id), maxseconds=maxseconds)\n  File \"/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 403, in wait_for\n    wait_on(func, what, walltime_exceeded)\n  File \"/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/wait.py\", line 38, in wait_on\n    value = function()\n            ^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 399, in \u003clambda\u003e\n    self.wait_for(lambda: self.__job_ready(job_id, history_id), maxseconds=maxseconds)\n                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 747, in __job_ready\n    return self._state_ready(job_id, error_msg=\"Job in error state.\")\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 839, in _state_ready\n    raise Exception(\nException: Job in error state.. tool_id: __DATA_FETCH__, exit_code: None, stderr: .\n", "status": "error", "test_index": 1, "time_seconds": 10.668724060058594, "tool_id": "bcftools_plugin_fill_tags", "tool_version": "1.15.1+galaxy4"}
            ]]></error>
        
    </testcase>
    
    <testcase classname="circos (Test #1)" name="0" time="51.35395288467407">
        
            
                <error type="error" message="Tool exit code: None"><![CDATA[
                    { "inputs": {  "outputs|png": true,  "outputs|svg": true,  "reference_genome|ref|genome_fasta": {   "id": "4b40fb32cdc04ffc",   "src": "hda"  },  "reference_genome|ref|ref_source": "history" }, "job": {  "command_line": "mkdir -p circos/conf/ circos/data/ \u0026\u0026  ln -s \u0027/galaxy/server/database/objects/8/e/5/dataset_8e5f7656-bfb9-49ca-8dc5-a73111e7e6e5.dat\u0027 genomeref.fa \u0026\u0026  python \u0027/cvmfs/cloud.galaxyproject.org/tools/toolshed.g2.bx.psu.edu/repos/iuc/circos/df7356989ac1/circos/karyotype-from-fasta.py\u0027 genomeref.fa \u003e circos/conf/karyotype.txt \u0026\u0026  python \u0027/cvmfs/cloud.galaxyproject.org/tools/toolshed.g2.bx.psu.edu/repos/iuc/circos/df7356989ac1/circos/karyotype-colors.py\u0027 `grep -c \u0027^chr\\s\u0027 \u0027circos/conf/karyotype.txt\u0027` \u003e \u0027circos/conf/karyotype-colors.conf\u0027 \u0026\u0026  touch circos/conf/karyotype-colors.conf \u0026\u0026    cp \u0027/galaxy/server/database/jobs_directory/000/104/configs/tmp3gcivvh4\u0027 circos/conf/circos.conf \u0026\u0026 cp \u0027/galaxy/server/database/jobs_directory/000/104/configs/tmp7likjo_y\u0027 circos/conf/ticks.conf \u0026\u0026 cp \u0027/galaxy/server/database/jobs_directory/000/104/configs/tmp4q05968x\u0027 circos/conf/ideogram.conf \u0026\u0026 cp \u0027/galaxy/server/database/jobs_directory/000/104/configs/tmpcw3sg8x7\u0027  circos/conf/data.conf \u0026\u0026 cp \u0027/galaxy/server/database/jobs_directory/000/104/configs/tmpvo86js22\u0027  circos/conf/links.conf \u0026\u0026 cp \u0027/galaxy/server/database/jobs_directory/000/104/configs/tmprcx8lfft\u0027 circos/conf/galaxy_test_case.json \u0026\u0026     circos -conf circos/conf/circos.conf -noparanoid",  "command_version": null,  "copied_from_job_id": null,  "create_time": "2025-03-13T01:18:32.255778",  "dependencies": [],  "exit_code": null,  "external_id": "gxy-z6khc",  "galaxy_version": "24.1",  "handler": null,  "history_id": "dcfa6e939a7a2524",  "id": "9a341591364ccd43",  "inputs": {   "reference_genome|ref|genome_fasta": {    "id": "4b40fb32cdc04ffc",    "src": "hda",    "uuid": "8e5f7656-bfb9-49ca-8dc5-a73111e7e6e5"   }  },  "job_messages": null,  "job_metrics": [],  "job_runner_name": null,  "job_stderr": null,  "job_stdout": null,  "model_class": "Job",  "output_collections": {},  "outputs": {   "karyotype_txt": {    "id": "3c8f55d4cf28cd03",    "src": "hda",    "uuid": "6765a1d0-764f-4c02-9b24-798384755523"   },   "output_png": {    "id": "226f78dd8ea65f1d",    "src": "hda",    "uuid": "b1cfb591-e1f2-4ee7-aec8-056c4bb13af4"   },   "output_svg": {    "id": "d3027f3f0124088a",    "src": "hda",    "uuid": "c30683b1-17ae-4802-a812-349f610f5079"   }  },  "params": {   "__input_ext": "\"fasta\"",   "chromInfo": "\"/cvmfs/data.galaxyproject.org/managed/len/ucsc/?.len\"",   "dbkey": "\"?\"",   "ideogram": "{\"angle_offset\": \"-90\", \"angle_orientation\": \"clockwise\", \"bands\": {\"band_stroke_color\": \"#000000\", \"band_stroke_thickness\": \"0\", \"band_transparency\": \"3\", \"fill_bands\": true, \"show_bands\": true}, \"chromosomes_reverse\": null, \"ideogram_labels\": {\"parallel\": true, \"radius_offset\": \"0.075\", \"show_label\": true, \"size\": \"24\"}, \"limit_chromosomes\": null, \"pairwise_spacing\": [], \"radius\": \"0.9\", \"spacing\": \"0.5\", \"thickness\": \"30.0\", \"units\": \"mb\"}",   "limits": "{\"max_ideograms\": \"200\", \"max_links\": \"25000\", \"max_points_per_track\": \"25000\", \"max_ticks\": \"5000\"}",   "outputs": "{\"png\": true, \"svg\": true, \"tar\": false}",   "plot_options": "{\"background\": {\"__current_case__\": 1, \"background_color\": \"#ffffff\", \"background_select\": \"color\"}, \"colour_profile\": null, \"radius\": \"1500\"}",   "reference_genome": "{\"ref\": {\"__current_case__\": 2, \"genome_fasta\": {\"values\": [{\"id\": 117, \"src\": \"hda\"}]}, \"ref_source\": \"history\"}}",   "scaling": "{\"zooms\": []}",   "sec_links": "{\"data\": []}",   "sec_tdd": "{\"data\": []}",   "ticks": "{\"radius\": \"1.0\", \"skip_first_label\": false, \"skip_last_label\": false, \"tick_group\": []}"  },  "state": "error",  "stderr": "Use of uninitialized value in subroutine entry at /usr/local/bin/../lib/Circos/Configuration.pm line 781.\n",  "stdout": "debuggroup summary 0.13s welcome to circos v0.69-8 15 Jun 2019 on Perl 5.026002\ndebuggroup summary 0.13s current working directory /galaxy/server/database/jobs_directory/000/104/working\ndebuggroup summary 0.13s command /usr/local/bin/circos -conf circos/conf/circos.conf -noparanoid\ndebuggroup summary 0.13s loading configuration from file circos/conf/circos.conf\ndebuggroup summary 0.13s found conf file circos/conf/circos.conf\ndebuggroup summary 0.25s debug will appear for these features: output,summary\ndebuggroup summary 0.25s bitmap output image ./circos.png\ndebuggroup summary 0.26s SVG output image ./circos.svg\ndebuggroup summary 0.26s parsing karyotype and organizing ideograms\ndebuggroup summary 0.26s karyotype has 2 chromosomes of total size 56,082\ndebuggroup summary 0.26s applying global and local scaling\ndebuggroup summary 0.26s allocating image, colors and brushes\ndebuggroup summary 5.44s drawing 2 ideograms of total size 56,082\ndebuggroup summary 5.44s drawing highlights and ideograms\ndebuggroup output 5.45s generating output\ndebuggroup output 5.74s created PNG image ./circos.png (40 kb)\ndebuggroup output 5.74s created SVG image ./circos.svg (2 kb)\n",  "tool_id": "toolshed.g2.bx.psu.edu/repos/iuc/circos/circos/0.69.8+galaxy7",  "tool_stderr": "Use of uninitialized value in subroutine entry at /usr/local/bin/../lib/Circos/Configuration.pm line 781.\n",  "tool_stdout": "debuggroup summary 0.13s welcome to circos v0.69-8 15 Jun 2019 on Perl 5.026002\ndebuggroup summary 0.13s current working directory /galaxy/server/database/jobs_directory/000/104/working\ndebuggroup summary 0.13s command /usr/local/bin/circos -conf circos/conf/circos.conf -noparanoid\ndebuggroup summary 0.13s loading configuration from file circos/conf/circos.conf\ndebuggroup summary 0.13s found conf file circos/conf/circos.conf\ndebuggroup summary 0.25s debug will appear for these features: output,summary\ndebuggroup summary 0.25s bitmap output image ./circos.png\ndebuggroup summary 0.26s SVG output image ./circos.svg\ndebuggroup summary 0.26s parsing karyotype and organizing ideograms\ndebuggroup summary 0.26s karyotype has 2 chromosomes of total size 56,082\ndebuggroup summary 0.26s applying global and local scaling\ndebuggroup summary 0.26s allocating image, colors and brushes\ndebuggroup summary 5.44s drawing 2 ideograms of total size 56,082\ndebuggroup summary 5.44s drawing highlights and ideograms\ndebuggroup output 5.45s generating output\ndebuggroup output 5.74s created PNG image ./circos.png (40 kb)\ndebuggroup output 5.74s created SVG image ./circos.svg (2 kb)\n",  "update_time": "2025-03-13T01:19:04.218269",  "user_email": "tests@fake.org" }, "output_problems": [  "Job in error state.. tool_id: toolshed.g2.bx.psu.edu/repos/iuc/circos/circos/0.69.8+galaxy7, exit_code: None, stderr: Use of uninitialized value in subroutine entry at /usr/local/bin/../lib/Circos/Configuration.pm line 781.\n.",  "Job in error state.. tool_id: toolshed.g2.bx.psu.edu/repos/iuc/circos/circos/0.69.8+galaxy7, exit_code: None, stderr: Use of uninitialized value in subroutine entry at /usr/local/bin/../lib/Circos/Configuration.pm line 781.\n.",  "Job in error state.. tool_id: toolshed.g2.bx.psu.edu/repos/iuc/circos/circos/0.69.8+galaxy7, exit_code: None, stderr: Use of uninitialized value in subroutine entry at /usr/local/bin/../lib/Circos/Configuration.pm line 781.\n." ], "status": "failure", "test_index": 0, "time_seconds": 51.35395288467407, "tool_id": "circos", "tool_version": "0.69.8+galaxy7"}
                ]]></error>
            
            <system-out><![CDATA[
            debuggroup summary 0.13s welcome to circos v0.69-8 15 Jun 2019 on Perl 5.026002debuggroup summary 0.13s current working directory /galaxy/server/database/jobs_directory/000/104/workingdebuggroup summary 0.13s command /usr/local/bin/circos -conf circos/conf/circos.conf -noparanoiddebuggroup summary 0.13s loading configuration from file circos/conf/circos.confdebuggroup summary 0.13s found conf file circos/conf/circos.confdebuggroup summary 0.25s debug will appear for these features: output,summarydebuggroup summary 0.25s bitmap output image ./circos.pngdebuggroup summary 0.26s SVG output image ./circos.svgdebuggroup summary 0.26s parsing karyotype and organizing ideogramsdebuggroup summary 0.26s karyotype has 2 chromosomes of total size 56,082debuggroup summary 0.26s applying global and local scalingdebuggroup summary 0.26s allocating image, colors and brushesdebuggroup summary 5.44s drawing 2 ideograms of total size 56,082debuggroup summary 5.44s drawing highlights and ideogramsdebuggroup output 5.45s generating outputdebuggroup output 5.74s created PNG image ./circos.png (40 kb)debuggroup output 5.74s created SVG image ./circos.svg (2 kb)
            ]]></system-out>
            <system-err><![CDATA[
            Use of uninitialized value in subroutine entry at /usr/local/bin/../lib/Circos/Configuration.pm line 781.
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="circos (Test #2)" name="1" time="49.161598920822144">
        
            
            <system-out><![CDATA[
            debuggroup summary 0.13s welcome to circos v0.69-8 15 Jun 2019 on Perl 5.026002debuggroup summary 0.13s current working directory /galaxy/server/database/jobs_directory/000/109/workingdebuggroup summary 0.13s command /usr/local/bin/circos -conf circos/conf/circos.conf -noparanoiddebuggroup summary 0.13s loading configuration from file circos/conf/circos.confdebuggroup summary 0.13s found conf file circos/conf/circos.confdebuggroup summary 0.24s debug will appear for these features: output,summarydebuggroup summary 0.24s bitmap output image ./circos.pngdebuggroup summary 0.24s SVG output image ./circos.svgdebuggroup summary 0.24s parsing karyotype and organizing ideogramsdebuggroup summary 0.25s karyotype has 2 chromosomes of total size 56,082debuggroup summary 0.25s applying global and local scalingdebuggroup summary 0.25s allocating image, colors and brushesdebuggroup summary 5.03s drawing 2 ideograms of total size 56,082debuggroup summary 5.03s drawing highlights and ideogramsdebuggroup summary 5.07s found conf file /usr/local/bin/../etc/tracks/link.confdebuggroup summary 5.08s process track_0 link circos/conf/../data/links-0.txtdebuggroup summary 5.08s drawing link track_0 z 0debuggroup !circoswarning 5.11s  Data point of type [link] [50000-50500] extended past end of ideogram [ctgA 0-50001]. This data point will be [trimmed].debuggroup !circoswarning 5.11s  Data point of type [link] [51000-51500] extended past end of ideogram [ctgA 0-50001]. This data point will be [hidden].debuggroup summary 5.11s found conf file /usr/local/bin/../etc/tracks/histogram.confdebuggroup summary 5.11s found conf file /usr/local/bin/../etc/tracks/scatter.confdebuggroup summary 5.11s found conf file /usr/local/bin/../etc/tracks/tile.confdebuggroup summary 5.12s processing track_0 histogram circos/conf/../data/data-0.txtdebuggroup summary 5.18s processing track_1 scatter circos/conf/../data/data-1.txtdebuggroup summary 5.30s processing track_2 tile circos/conf/../data/data-2.txtdebuggroup summary 5.32s drawing track_0 histogram z 0 data-0.txt orient outdebuggroup summary 5.33s found conf file /usr/local/bin/../etc/tracks/axis.confdebuggroup summary 5.90s drawing track_1 scatter z 0 data-1.txt orient outdebuggroup summary 5.91s found conf file /usr/local/bin/../etc/tracks/axis.confdebuggroup summary 6.07s drawing track_2 tile z 0 data-2.txt orient outdebuggroup summary 6.07s found conf file /usr/local/bin/../etc/tracks/axis.confdebuggroup !circoswarning 6.23s  Data point of type [tile] [3013-6130] extended past end of ideogram [ctgB 0-6079]. This data point will be [trimmed].debuggroup output 6.23s generating outputdebuggroup output 6.60s created PNG image ./circos.png (539 kb)debuggroup output 6.62s created SVG image ./circos.svg (414 kb)
            ]]></system-out>
            <system-err><![CDATA[
            Use of uninitialized value in subroutine entry at /usr/local/bin/../lib/Circos/Configuration.pm line 781.Use of uninitialized value in subroutine entry at /usr/local/bin/../lib/Circos/Configuration.pm line 781.Use of uninitialized value within %Circos::Error::GROUPERROR in uc at /usr/local/bin/../lib/Circos/Error.pm line 354, <F> line 21.Use of uninitialized value within %Circos::Error::GROUPERROR in uc at /usr/local/bin/../lib/Circos/Error.pm line 354, <F> line 21.Use of uninitialized value in subroutine entry at /usr/local/bin/../lib/Circos/Configuration.pm line 781, <F> line 21.Use of uninitialized value in subroutine entry at /usr/local/bin/../lib/Circos/Configuration.pm line 781.Use of uninitialized value in subroutine entry at /usr/local/bin/../lib/Circos/Configuration.pm line 781.Use of uninitialized value in subroutine entry at /usr/local/bin/../lib/Circos/Configuration.pm line 781, <F> line 1214.Use of uninitialized value in subroutine entry at /usr/local/bin/../lib/Circos/Configuration.pm line 781.Use of uninitialized value in subroutine entry at /usr/local/bin/../lib/Circos/Configuration.pm line 781.Use of uninitialized value within %Circos::Error::GROUPERROR in uc at /usr/local/bin/../lib/Circos/Error.pm line 354.
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="deeptools_plot_enrichment (Test #1)" name="0" time="58.804927110672">
        
            
            <system-out><![CDATA[
            
            ]]></system-out>
            <system-err><![CDATA[
            
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="filter_tabular (Test #1)" name="0" time="69.8892993927002">
        
            
            <system-out><![CDATA[
            
            ]]></system-out>
            <system-err><![CDATA[
            
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="filter_tabular (Test #2)" name="1" time="31.83279800415039">
        
            
            <system-out><![CDATA[
            
            ]]></system-out>
            <system-err><![CDATA[
            
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="filter_tabular (Test #3)" name="2" time="34.07917523384094">
        
            
            <system-out><![CDATA[
            
            ]]></system-out>
            <system-err><![CDATA[
            
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="filter_tabular (Test #4)" name="3" time="29.93018412590027">
        
            
            <system-out><![CDATA[
            
            ]]></system-out>
            <system-err><![CDATA[
            
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="filter_tabular (Test #5)" name="4" time="32.245447397232056">
        
            
            <system-out><![CDATA[
            
            ]]></system-out>
            <system-err><![CDATA[
            
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="flash (Test #1)" name="0" time="11.684065103530884">
        
            <error type="error" message="Input staging problem: Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 1434, in verify_tool
    stage_data_in_history(
  File "/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 175, in stage_data_in_history
    staging_interface.handle_jobs()
  File "/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 212, in handle_jobs
    self.galaxy_interactor.wait_for_job(job_response["id"], job_response["history_id"], self.maxseconds)
  File "/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 399, in wait_for_job
    self.wait_for(lambda: self.__job_ready(job_id, history_id), maxseconds=maxseconds)
  File "/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 403, in wait_for
    wait_on(func, what, walltime_exceeded)
  File "/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/wait.py", line 38, in wait_on
    value = function()
            ^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 399, in <lambda>
    self.wait_for(lambda: self.__job_ready(job_id, history_id), maxseconds=maxseconds)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 747, in __job_ready
    return self._state_ready(job_id, error_msg="Job in error state.")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 839, in _state_ready
    raise Exception(
Exception: Job in error state.. tool_id: __DATA_FETCH__, exit_code: None, stderr: .
"><![CDATA[
                { "execution_problem": "Input staging problem: Traceback (most recent call last):\n  File \"/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 1434, in verify_tool\n    stage_data_in_history(\n  File \"/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 175, in stage_data_in_history\n    staging_interface.handle_jobs()\n  File \"/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 212, in handle_jobs\n    self.galaxy_interactor.wait_for_job(job_response[\"id\"], job_response[\"history_id\"], self.maxseconds)\n  File \"/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 399, in wait_for_job\n    self.wait_for(lambda: self.__job_ready(job_id, history_id), maxseconds=maxseconds)\n  File \"/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 403, in wait_for\n    wait_on(func, what, walltime_exceeded)\n  File \"/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/wait.py\", line 38, in wait_on\n    value = function()\n            ^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 399, in \u003clambda\u003e\n    self.wait_for(lambda: self.__job_ready(job_id, history_id), maxseconds=maxseconds)\n                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 747, in __job_ready\n    return self._state_ready(job_id, error_msg=\"Job in error state.\")\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 839, in _state_ready\n    raise Exception(\nException: Job in error state.. tool_id: __DATA_FETCH__, exit_code: None, stderr: .\n", "status": "error", "test_index": 0, "time_seconds": 11.684065103530884, "tool_id": "flash", "tool_version": "1.2.11.4"}
            ]]></error>
        
    </testcase>
    
    <testcase classname="flash (Test #2)" name="1" time="12.331067323684692">
        
            <error type="error" message="Input staging problem: Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 1434, in verify_tool
    stage_data_in_history(
  File "/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 175, in stage_data_in_history
    staging_interface.handle_jobs()
  File "/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 212, in handle_jobs
    self.galaxy_interactor.wait_for_job(job_response["id"], job_response["history_id"], self.maxseconds)
  File "/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 399, in wait_for_job
    self.wait_for(lambda: self.__job_ready(job_id, history_id), maxseconds=maxseconds)
  File "/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 403, in wait_for
    wait_on(func, what, walltime_exceeded)
  File "/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/wait.py", line 38, in wait_on
    value = function()
            ^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 399, in <lambda>
    self.wait_for(lambda: self.__job_ready(job_id, history_id), maxseconds=maxseconds)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 747, in __job_ready
    return self._state_ready(job_id, error_msg="Job in error state.")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 839, in _state_ready
    raise Exception(
Exception: Job in error state.. tool_id: __DATA_FETCH__, exit_code: None, stderr: .
"><![CDATA[
                { "execution_problem": "Input staging problem: Traceback (most recent call last):\n  File \"/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 1434, in verify_tool\n    stage_data_in_history(\n  File \"/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 175, in stage_data_in_history\n    staging_interface.handle_jobs()\n  File \"/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 212, in handle_jobs\n    self.galaxy_interactor.wait_for_job(job_response[\"id\"], job_response[\"history_id\"], self.maxseconds)\n  File \"/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 399, in wait_for_job\n    self.wait_for(lambda: self.__job_ready(job_id, history_id), maxseconds=maxseconds)\n  File \"/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 403, in wait_for\n    wait_on(func, what, walltime_exceeded)\n  File \"/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/wait.py\", line 38, in wait_on\n    value = function()\n            ^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 399, in \u003clambda\u003e\n    self.wait_for(lambda: self.__job_ready(job_id, history_id), maxseconds=maxseconds)\n                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 747, in __job_ready\n    return self._state_ready(job_id, error_msg=\"Job in error state.\")\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 839, in _state_ready\n    raise Exception(\nException: Job in error state.. tool_id: __DATA_FETCH__, exit_code: None, stderr: .\n", "status": "error", "test_index": 1, "time_seconds": 12.331067323684692, "tool_id": "flash", "tool_version": "1.2.11.4"}
            ]]></error>
        
    </testcase>
    
    <testcase classname="flash (Test #3)" name="2" time="37.43226981163025">
        
            
            <system-out><![CDATA[
            [FLASH] Starting FLASH v1.2.11[FLASH] Fast Length Adjustment of SHort reads[FLASH]  [FLASH] Input files:[FLASH]     /galaxy/server/database/objects/a/6/2/dataset_a62e8d5f-df4d-4c6f-bde2-3cc70b70ee83.dat[FLASH]     /galaxy/server/database/objects/b/c/4/dataset_bc46fc94-2225-4cc1-88e0-499afde50661.dat[FLASH]  [FLASH] Output files:[FLASH]     ./out.extendedFrags.fastq[FLASH]     ./out.notCombined_1.fastq[FLASH]     ./out.notCombined_2.fastq[FLASH]     ./out.hist[FLASH]     ./out.histogram[FLASH]  [FLASH] Parameters:[FLASH]     Min overlap:           10[FLASH]     Max overlap:           65[FLASH]     Max mismatch density:  0.250000[FLASH]     Allow "outie" pairs:   false[FLASH]     Cap mismatch quals:    false[FLASH]     Combiner threads:      1[FLASH]     Input format:          FASTQ, phred_offset=64[FLASH]     Output format:         FASTQ, phred_offset=64[FLASH]  [FLASH] Starting reader and writer threads[FLASH] Starting 1 combiner threads[FLASH] Processed 200 read pairs[FLASH]  [FLASH] Read combination statistics:[FLASH]     Total pairs:      200[FLASH]     Combined pairs:   5[FLASH]     Uncombined pairs: 195[FLASH]     Percent combined: 2.50%[FLASH]  [FLASH] Writing histogram files.[FLASH]  [FLASH] FLASH v1.2.11 complete![FLASH] 0.023 seconds elapsed
            ]]></system-out>
            <system-err><![CDATA[
            
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="flash (Test #4)" name="3" time="36.35432004928589">
        
            
            <system-out><![CDATA[
            
            ]]></system-out>
            <system-err><![CDATA[
            
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="flash (Test #5)" name="4" time="34.789555311203">
        
            
            <system-out><![CDATA[
            [FLASH] Starting FLASH v1.2.11[FLASH] Fast Length Adjustment of SHort reads[FLASH]  [FLASH] Input files:[FLASH]     /galaxy/server/database/objects/7/2/4/dataset_7249cabd-80c0-4b79-b93f-5a199d341ec8.dat[FLASH]     /galaxy/server/database/objects/4/5/3/dataset_4536ca32-acc1-49f5-9fec-3f504e15f4bf.dat[FLASH]  [FLASH] Output files:[FLASH]     ./out.extendedFrags.fastq[FLASH]     ./out.notCombined_1.fastq[FLASH]     ./out.notCombined_2.fastq[FLASH]     ./out.hist[FLASH]     ./out.histogram[FLASH]  [FLASH] Parameters:[FLASH]     Min overlap:           10[FLASH]     Max overlap:           65[FLASH]     Max mismatch density:  0.250000[FLASH]     Allow "outie" pairs:   false[FLASH]     Cap mismatch quals:    false[FLASH]     Combiner threads:      1[FLASH]     Input format:          FASTQ, phred_offset=33[FLASH]     Output format:         FASTQ, phred_offset=33, gzip[FLASH]  [FLASH] Starting reader and writer threads[FLASH] Starting 1 combiner threads[FLASH] Processed 500 read pairs[FLASH]  [FLASH] Read combination statistics:[FLASH]     Total pairs:      500[FLASH]     Combined pairs:   18[FLASH]     Uncombined pairs: 482[FLASH]     Percent combined: 3.60%[FLASH]  [FLASH] Writing histogram files.[FLASH]  [FLASH] FLASH v1.2.11 complete![FLASH] 0.041 seconds elapsed
            ]]></system-out>
            <system-err><![CDATA[
            
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="ivar_filtervariants (Test #1)" name="0" time="39.6186785697937">
        
            
            <system-out><![CDATA[
            Header format of ./var_0.tsv did not match! Please use files generated using "ivar variants" command.
            ]]></system-out>
            <system-err><![CDATA[
            
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="medaka_consensus (Test #1)" name="0" time="75.93002772331238">
        
            
            <system-out><![CDATA[
            [01:12:12 - Predict] Reducing threads to 2, anymore is a waste.[01:12:12 - Predict] It looks like you are running medaka without a GPU and attempted to set a high number of threads. We have scaled this down to an optimal number. If you wish to improve performance please see https://nanoporetech.github.io/medaka/installation.html#improving-parallelism.[01:12:12 - Predict] Setting tensorflow inter/intra-op threads to 2/1.[01:12:12 - Predict] Processing region(s): ref:0-30[01:12:12 - Predict] Using model: /usr/local/lib/python3.8/site-packages/medaka/data/r941_min_high_g360_model.hdf5.[01:12:12 - DataStre] Writing sample registry.[01:12:12 - Predict] Processing 1 long region(s) with batching.[01:12:12 - MdlStore] filepath /usr/local/lib/python3.8/site-packages/medaka/data/r941_min_high_g360_model.hdf52025-03-13 01:12:12.028145: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE4.1 SSE4.2 AVX AVX2 FMATo enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.[01:12:12 - BAMFile] Creating pool of 16 BAM file sets.[01:12:12 - DLoader] Sample-0: started[01:12:12 - Sampler] Initializing sampler for consensus of region ref:0-30.[01:12:12 - DLoader] Sample-1: started[01:12:12 - DLoader] Sample-1: finished[01:12:12 - Feature] Pileup counts do not span requested region, requested ref:0-30, received 0-9.[01:12:12 - DLoader] Initialised. Batch size:100. Workers:2. Cache:800[01:12:12 - PWorker] Running inference for 0.0M draft bases.[01:12:12 - Feature] Processed ref:0.0-9.0 (median depth 1.0)[01:12:12 - Feature] Pileup counts do not span requested region, requested ref:0-30, received 14-29.[01:12:12 - Feature] Processed ref:14.0-29.0 (median depth 1.0)[01:12:12 - Sampler] Took 0.03s to make features.[01:12:12 - Sampler] Region ref:0.0-9.0 (10 positions) is smaller than inference chunk length 10000, quarantining.[01:12:12 - Sampler] Region ref:14.0-29.0 (16 positions) is smaller than inference chunk length 10000, quarantining.[01:12:12 - DLoader] Sample-0: finished[01:12:12 - DLoader] Batches ready: 0. Samples ready: 0 (0.0 batches)[01:12:12 - DataStre] Writing sample registry.[01:12:12 - PWorker] Processed 0 batches[01:12:12 - PWorker] All done, 2 remainder regions.[01:12:12 - Predict] Processing 2 short region(s).[01:12:12 - MdlStore] filepath /usr/local/lib/python3.8/site-packages/medaka/data/r941_min_high_g360_model.hdf5[01:12:13 - DLoader] Sample-0: started[01:12:13 - Sampler] Initializing sampler for consensus of region ref:0-10.[01:12:13 - DLoader] Sample-1: started[01:12:13 - Sampler] Initializing sampler for consensus of region ref:14-30.[01:12:13 - Feature] Processed ref:0.0-9.0 (median depth 1.0)[01:12:13 - Sampler] Took 0.00s to make features.[01:12:13 - Sampler] Pileup for ref:0.0-9.0 is of width 10[01:12:13 - DLoader] Initialised. Batch size:1. Workers:2. Cache:8[01:12:13 - PWorker] Running inference for 0.0M draft bases.[01:12:13 - DLoader] Sample-0: finished[01:12:13 - Feature] Processed ref:14.0-29.0 (median depth 1.0)[01:12:13 - Sampler] Took 0.02s to make features.[01:12:13 - Sampler] Pileup for ref:14.0-29.0 is of width 16[01:12:13 - DLoader] Batches ready: 0. Samples ready: 0 (0.0 batches)[01:12:13 - DLoader] Sample-1: finished[01:12:13 - DataStre] Loaded sample register.[01:12:13 - DataStre] Adding ref:0.0-9.0 to sample registry[01:12:13 - DLoader] Batches ready: 1. Samples ready: 0 (0.0 batches)[01:12:13 - DataStre] Adding ref:14.0-29.0 to sample registry[01:12:13 - DLoader] Batches ready: 0. Samples ready: 0 (0.0 batches)[01:12:13 - DataStre] Writing sample registry.[01:12:13 - PWorker] Processed 2 batches[01:12:13 - PWorker] All done, 0 remainder regions.[01:12:13 - Predict] Finished processing all regions.[01:12:13 - BAMFile] Closing BAM file set.[01:12:13 - BAMFile] Closing BAM file set.[01:12:13 - BAMFile] Closing BAM file set.[01:12:13 - BAMFile] Closing BAM file set.[01:12:13 - BAMFile] Closing BAM file set.[01:12:13 - BAMFile] Closing BAM file set.[01:12:13 - BAMFile] Closing BAM file set.[01:12:13 - BAMFile] Closing BAM file set.[01:12:13 - BAMFile] Closing BAM file set.[01:12:13 - BAMFile] Closing BAM file set.[01:12:13 - BAMFile] Closing BAM file set.[01:12:13 - BAMFile] Closing BAM file set.[01:12:13 - BAMFile] Closing BAM file set.[01:12:13 - BAMFile] Closing BAM file set.[01:12:13 - BAMFile] Closing BAM file set.[01:12:13 - BAMFile] Closing BAM file set.
            ]]></system-out>
            <system-err><![CDATA[
            
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="medaka_consensus (Test #2)" name="1" time="39.51445484161377">
        
            
            <system-out><![CDATA[
            [01:13:00 - Predict] Reducing threads to 2, anymore is a waste.[01:13:00 - Predict] It looks like you are running medaka without a GPU and attempted to set a high number of threads. We have scaled this down to an optimal number. If you wish to improve performance please see https://nanoporetech.github.io/medaka/installation.html#improving-parallelism.[01:13:00 - Predict] Setting tensorflow inter/intra-op threads to 2/1.[01:13:00 - Predict] Processing region(s): ref:0-30[01:13:00 - Predict] Using model: /usr/local/lib/python3.8/site-packages/medaka/data/r941_min_fast_g303_model.hdf5.[01:13:00 - DataStre] Writing sample registry.[01:13:00 - Predict] Processing 1 long region(s) with batching.[01:13:00 - MdlStore] filepath /usr/local/lib/python3.8/site-packages/medaka/data/r941_min_fast_g303_model.hdf52025-03-13 01:13:00.124138: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE4.1 SSE4.2 AVX AVX2 FMATo enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.[01:13:00 - BAMFile] Creating pool of 16 BAM file sets.[01:13:00 - DLoader] Sample-0: started[01:13:00 - Sampler] Initializing sampler for consensus of region ref:0-30.[01:13:00 - DLoader] Sample-1: started[01:13:00 - DLoader] Sample-1: finished[01:13:00 - DLoader] Initialised. Batch size:99. Workers:2. Cache:792[01:13:00 - PWorker] Running inference for 0.0M draft bases.[01:13:00 - Feature] Pileup counts do not span requested region, requested ref:0-30, received 0-9.[01:13:00 - Feature] Processed ref:0.0-9.0 (median depth 1.0)[01:13:00 - Feature] Pileup counts do not span requested region, requested ref:0-30, received 14-29.[01:13:00 - Feature] Processed ref:14.0-29.0 (median depth 1.0)[01:13:00 - Sampler] Took 0.03s to make features.[01:13:00 - Sampler] Region ref:0.0-9.0 (10 positions) is smaller than inference chunk length 9999, quarantining.[01:13:00 - Sampler] Region ref:14.0-29.0 (16 positions) is smaller than inference chunk length 9999, quarantining.[01:13:00 - DLoader] Sample-0: finished[01:13:00 - DLoader] Batches ready: 0. Samples ready: 0 (0.0 batches)[01:13:00 - DataStre] Writing sample registry.[01:13:00 - PWorker] Processed 0 batches[01:13:00 - PWorker] All done, 2 remainder regions.[01:13:00 - Predict] Processing 2 short region(s).[01:13:00 - MdlStore] filepath /usr/local/lib/python3.8/site-packages/medaka/data/r941_min_fast_g303_model.hdf5[01:13:01 - DLoader] Sample-0: started[01:13:01 - Sampler] Initializing sampler for consensus of region ref:0-10.[01:13:01 - DLoader] Sample-1: started[01:13:01 - Sampler] Initializing sampler for consensus of region ref:14-30.[01:13:01 - Feature] Processed ref:0.0-9.0 (median depth 1.0)[01:13:01 - Sampler] Took 0.00s to make features.[01:13:01 - Sampler] Pileup for ref:0.0-9.0 is of width 10[01:13:01 - DLoader] Sample-0: finished[01:13:01 - DLoader] Initialised. Batch size:1. Workers:2. Cache:8[01:13:01 - PWorker] Running inference for 0.0M draft bases.[01:13:01 - Feature] Processed ref:14.0-29.0 (median depth 1.0)[01:13:01 - DLoader] Batches ready: 0. Samples ready: 0 (0.0 batches)[01:13:01 - Sampler] Took 0.02s to make features.[01:13:01 - Sampler] Pileup for ref:14.0-29.0 is of width 16[01:13:01 - DLoader] Sample-1: finished[01:13:01 - DataStre] Loaded sample register.[01:13:01 - DataStre] Adding ref:0.0-9.0 to sample registry[01:13:01 - DLoader] Batches ready: 1. Samples ready: 0 (0.0 batches)[01:13:01 - DataStre] Adding ref:14.0-29.0 to sample registry[01:13:01 - DLoader] Batches ready: 0. Samples ready: 0 (0.0 batches)[01:13:01 - DataStre] Writing sample registry.[01:13:01 - PWorker] Processed 2 batches[01:13:01 - PWorker] All done, 0 remainder regions.[01:13:01 - Predict] Finished processing all regions.[01:13:01 - Predict] Validating and finalising output data.[01:13:01 - DataStre] Writing sample registry.[01:13:01 - DataStre] Created missing sample register.[01:13:01 - BAMFile] Closing BAM file set.[01:13:01 - BAMFile] Closing BAM file set.[01:13:01 - BAMFile] Closing BAM file set.[01:13:01 - BAMFile] Closing BAM file set.[01:13:01 - BAMFile] Closing BAM file set.[01:13:01 - BAMFile] Closing BAM file set.[01:13:01 - BAMFile] Closing BAM file set.[01:13:01 - BAMFile] Closing BAM file set.[01:13:01 - BAMFile] Closing BAM file set.[01:13:01 - BAMFile] Closing BAM file set.[01:13:01 - BAMFile] Closing BAM file set.[01:13:01 - BAMFile] Closing BAM file set.[01:13:01 - BAMFile] Closing BAM file set.[01:13:01 - BAMFile] Closing BAM file set.[01:13:01 - BAMFile] Closing BAM file set.[01:13:01 - BAMFile] Closing BAM file set.
            ]]></system-out>
            <system-err><![CDATA[
            
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="poretools_nucdist (Test #1)" name="0" time="68.03217935562134">
        
            
            <system-out><![CDATA[
            
            ]]></system-out>
            <system-err><![CDATA[
            
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="poretools_nucdist (Test #2)" name="1" time="33.352128982543945">
        
            
            <system-out><![CDATA[
            
            ]]></system-out>
            <system-err><![CDATA[
            
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="qualimap_multi_bamqc (Test #1)" name="0" time="46.1206636428833">
        
            <error type="error" message="Input staging problem: Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 1434, in verify_tool
    stage_data_in_history(
  File "/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 175, in stage_data_in_history
    staging_interface.handle_jobs()
  File "/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 212, in handle_jobs
    self.galaxy_interactor.wait_for_job(job_response["id"], job_response["history_id"], self.maxseconds)
  File "/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 399, in wait_for_job
    self.wait_for(lambda: self.__job_ready(job_id, history_id), maxseconds=maxseconds)
  File "/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 403, in wait_for
    wait_on(func, what, walltime_exceeded)
  File "/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/wait.py", line 38, in wait_on
    value = function()
            ^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 399, in <lambda>
    self.wait_for(lambda: self.__job_ready(job_id, history_id), maxseconds=maxseconds)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 747, in __job_ready
    return self._state_ready(job_id, error_msg="Job in error state.")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 839, in _state_ready
    raise Exception(
Exception: Job in error state.. tool_id: __DATA_FETCH__, exit_code: None, stderr: .
"><![CDATA[
                { "execution_problem": "Input staging problem: Traceback (most recent call last):\n  File \"/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 1434, in verify_tool\n    stage_data_in_history(\n  File \"/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 175, in stage_data_in_history\n    staging_interface.handle_jobs()\n  File \"/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 212, in handle_jobs\n    self.galaxy_interactor.wait_for_job(job_response[\"id\"], job_response[\"history_id\"], self.maxseconds)\n  File \"/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 399, in wait_for_job\n    self.wait_for(lambda: self.__job_ready(job_id, history_id), maxseconds=maxseconds)\n  File \"/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 403, in wait_for\n    wait_on(func, what, walltime_exceeded)\n  File \"/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/wait.py\", line 38, in wait_on\n    value = function()\n            ^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 399, in \u003clambda\u003e\n    self.wait_for(lambda: self.__job_ready(job_id, history_id), maxseconds=maxseconds)\n                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 747, in __job_ready\n    return self._state_ready(job_id, error_msg=\"Job in error state.\")\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 839, in _state_ready\n    raise Exception(\nException: Job in error state.. tool_id: __DATA_FETCH__, exit_code: None, stderr: .\n", "status": "error", "test_index": 0, "time_seconds": 46.1206636428833, "tool_id": "qualimap_multi_bamqc", "tool_version": "2.3+galaxy0"}
            ]]></error>
        
    </testcase>
    
    <testcase classname="racon (Test #1)" name="0" time="11.862982511520386">
        
            <error type="error" message="Input staging problem: Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 1434, in verify_tool
    stage_data_in_history(
  File "/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 175, in stage_data_in_history
    staging_interface.handle_jobs()
  File "/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 212, in handle_jobs
    self.galaxy_interactor.wait_for_job(job_response["id"], job_response["history_id"], self.maxseconds)
  File "/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 399, in wait_for_job
    self.wait_for(lambda: self.__job_ready(job_id, history_id), maxseconds=maxseconds)
  File "/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 403, in wait_for
    wait_on(func, what, walltime_exceeded)
  File "/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/wait.py", line 38, in wait_on
    value = function()
            ^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 399, in <lambda>
    self.wait_for(lambda: self.__job_ready(job_id, history_id), maxseconds=maxseconds)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 747, in __job_ready
    return self._state_ready(job_id, error_msg="Job in error state.")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 839, in _state_ready
    raise Exception(
Exception: Job in error state.. tool_id: __DATA_FETCH__, exit_code: None, stderr: .
"><![CDATA[
                { "execution_problem": "Input staging problem: Traceback (most recent call last):\n  File \"/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 1434, in verify_tool\n    stage_data_in_history(\n  File \"/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 175, in stage_data_in_history\n    staging_interface.handle_jobs()\n  File \"/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 212, in handle_jobs\n    self.galaxy_interactor.wait_for_job(job_response[\"id\"], job_response[\"history_id\"], self.maxseconds)\n  File \"/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 399, in wait_for_job\n    self.wait_for(lambda: self.__job_ready(job_id, history_id), maxseconds=maxseconds)\n  File \"/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 403, in wait_for\n    wait_on(func, what, walltime_exceeded)\n  File \"/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/wait.py\", line 38, in wait_on\n    value = function()\n            ^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 399, in \u003clambda\u003e\n    self.wait_for(lambda: self.__job_ready(job_id, history_id), maxseconds=maxseconds)\n                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 747, in __job_ready\n    return self._state_ready(job_id, error_msg=\"Job in error state.\")\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 839, in _state_ready\n    raise Exception(\nException: Job in error state.. tool_id: __DATA_FETCH__, exit_code: None, stderr: .\n", "status": "error", "test_index": 0, "time_seconds": 11.862982511520386, "tool_id": "racon", "tool_version": "1.5.0+galaxy1"}
            ]]></error>
        
    </testcase>
    
    <testcase classname="racon (Test #2)" name="1" time="45.14382290840149">
        
            
            <system-out><![CDATA[
            
            ]]></system-out>
            <system-err><![CDATA[
            [racon::Polisher::initialize] loaded target sequences 0.000858 s[racon::Polisher::initialize] loaded sequences 0.008641 s[racon::Polisher::initialize] loaded overlaps 0.000754 s[racon::Polisher::initialize] aligning overlaps [=>                  ] 0.011710 s[racon::Polisher::initialize] aligning overlaps [==>                 ] 0.020759 s[racon::Polisher::initialize] aligning overlaps [===>                ] 0.028741 s[racon::Polisher::initialize] aligning overlaps [====>               ] 0.031420 s[racon::Polisher::initialize] aligning overlaps [=====>              ] 0.036570 s[racon::Polisher::initialize] aligning overlaps [======>             ] 0.036805 s[racon::Polisher::initialize] aligning overlaps [=======>            ] 0.042939 s[racon::Polisher::initialize] aligning overlaps [========>           ] 0.049302 s[racon::Polisher::initialize] aligning overlaps [=========>          ] 0.052893 s[racon::Polisher::initialize] aligning overlaps [==========>         ] 0.056616 s[racon::Polisher::initialize] aligning overlaps [===========>        ] 0.057199 s[racon::Polisher::initialize] aligning overlaps [============>       ] 0.061153 s[racon::Polisher::initialize] aligning overlaps [=============>      ] 0.074433 s[racon::Polisher::initialize] aligning overlaps [==============>     ] 0.077202 s[racon::Polisher::initialize] aligning overlaps [===============>    ] 0.087032 s[racon::Polisher::initialize] aligning overlaps [================>   ] 0.089075 s[racon::Polisher::initialize] aligning overlaps [=================>  ] 0.090040 s[racon::Polisher::initialize] aligning overlaps [==================> ] 0.091360 s[racon::Polisher::initialize] aligning overlaps [===================>] 0.096449 s[racon::Polisher::initialize] aligning overlaps [====================] 0.096475 s[racon::Polisher::initialize] transformed data into windows 0.000336 s[racon::Polisher::polish] generating consensus [=>                  ] 0.015183 s[racon::Polisher::polish] generating consensus [==>                 ] 0.015845 s[racon::Polisher::polish] generating consensus [===>                ] 0.028614 s[racon::Polisher::polish] generating consensus [====>               ] 0.028740 s[racon::Polisher::polish] generating consensus [=====>              ] 0.037230 s[racon::Polisher::polish] generating consensus [======>             ] 0.037260 s[racon::Polisher::polish] generating consensus [=======>            ] 0.044051 s[racon::Polisher::polish] generating consensus [========>           ] 0.044157 s[racon::Polisher::polish] generating consensus [=========>          ] 0.051919 s[racon::Polisher::polish] generating consensus [==========>         ] 0.051960 s[racon::Polisher::polish] generating consensus [===========>        ] 0.067959 s[racon::Polisher::polish] generating consensus [============>       ] 0.067993 s[racon::Polisher::polish] generating consensus [=============>      ] 0.089272 s[racon::Polisher::polish] generating consensus [==============>     ] 0.094835 s[racon::Polisher::polish] generating consensus [===============>    ] 0.107844 s[racon::Polisher::polish] generating consensus [================>   ] 0.112626 s[racon::Polisher::polish] generating consensus [=================>  ] 0.124759 s[racon::Polisher::polish] generating consensus [==================> ] 0.126283 s[racon::Polisher::polish] generating consensus [===================>] 0.139001 s[racon::Polisher::polish] generating consensus [====================] 0.172777 s[racon::Polisher::] total = 0.284562 s
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="racon (Test #3)" name="2" time="37.484349966049194">
        
            
            <system-out><![CDATA[
            
            ]]></system-out>
            <system-err><![CDATA[
            [racon::Polisher::initialize] loaded target sequences 0.000927 s[racon::Polisher::initialize] loaded sequences 0.008625 s[racon::Polisher::initialize] loaded overlaps 0.010034 s[racon::Polisher::initialize] aligning overlaps [=>                  ] 0.002404 s[racon::Polisher::initialize] aligning overlaps [==>                 ] 0.002518 s[racon::Polisher::initialize] aligning overlaps [===>                ] 0.002693 s[racon::Polisher::initialize] aligning overlaps [====>               ] 0.002757 s[racon::Polisher::initialize] aligning overlaps [=====>              ] 0.002803 s[racon::Polisher::initialize] aligning overlaps [======>             ] 0.002915 s[racon::Polisher::initialize] aligning overlaps [=======>            ] 0.003140 s[racon::Polisher::initialize] aligning overlaps [========>           ] 0.003185 s[racon::Polisher::initialize] aligning overlaps [=========>          ] 0.003196 s[racon::Polisher::initialize] aligning overlaps [==========>         ] 0.003229 s[racon::Polisher::initialize] aligning overlaps [===========>        ] 0.003354 s[racon::Polisher::initialize] aligning overlaps [============>       ] 0.003412 s[racon::Polisher::initialize] aligning overlaps [=============>      ] 0.003491 s[racon::Polisher::initialize] aligning overlaps [==============>     ] 0.003564 s[racon::Polisher::initialize] aligning overlaps [===============>    ] 0.003586 s[racon::Polisher::initialize] aligning overlaps [================>   ] 0.003693 s[racon::Polisher::initialize] aligning overlaps [=================>  ] 0.003722 s[racon::Polisher::initialize] aligning overlaps [==================> ] 0.003829 s[racon::Polisher::initialize] aligning overlaps [===================>] 0.003840 s[racon::Polisher::initialize] aligning overlaps [====================] 0.003846 s[racon::Polisher::initialize] transformed data into windows 0.000524 s[racon::Polisher::polish] generating consensus [=>                  ] 0.033702 s[racon::Polisher::polish] generating consensus [==>                 ] 0.033805 s[racon::Polisher::polish] generating consensus [===>                ] 0.052196 s[racon::Polisher::polish] generating consensus [====>               ] 0.052279 s[racon::Polisher::polish] generating consensus [=====>              ] 0.060338 s[racon::Polisher::polish] generating consensus [======>             ] 0.060378 s[racon::Polisher::polish] generating consensus [=======>            ] 0.069405 s[racon::Polisher::polish] generating consensus [========>           ] 0.069490 s[racon::Polisher::polish] generating consensus [=========>          ] 0.083185 s[racon::Polisher::polish] generating consensus [==========>         ] 0.083769 s[racon::Polisher::polish] generating consensus [===========>        ] 0.106143 s[racon::Polisher::polish] generating consensus [============>       ] 0.109789 s[racon::Polisher::polish] generating consensus [=============>      ] 0.135819 s[racon::Polisher::polish] generating consensus [==============>     ] 0.143452 s[racon::Polisher::polish] generating consensus [===============>    ] 0.158481 s[racon::Polisher::polish] generating consensus [================>   ] 0.164255 s[racon::Polisher::polish] generating consensus [=================>  ] 0.175306 s[racon::Polisher::polish] generating consensus [==================> ] 0.176587 s[racon::Polisher::polish] generating consensus [===================>] 0.186794 s[racon::Polisher::polish] generating consensus [====================] 0.209858 s[racon::Polisher::] total = 0.237808 s
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="samtools_sort (Test #1)" name="0" time="36.31668996810913">
        
            
            <system-out><![CDATA[
            
            ]]></system-out>
            <system-err><![CDATA[
            
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="samtools_sort (Test #2)" name="1" time="32.03644061088562">
        
            
            <system-out><![CDATA[
            
            ]]></system-out>
            <system-err><![CDATA[
            
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="samtools_sort (Test #3)" name="2" time="32.13085913658142">
        
            
            <system-out><![CDATA[
            
            ]]></system-out>
            <system-err><![CDATA[
            
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="samtools_sort (Test #4)" name="3" time="33.45809888839722">
        
            
            <system-out><![CDATA[
            
            ]]></system-out>
            <system-err><![CDATA[
            
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="samtools_sort (Test #5)" name="4" time="31.355552911758423">
        
            
            <system-out><![CDATA[
            
            ]]></system-out>
            <system-err><![CDATA[
            
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="samtools_sort (Test #6)" name="5" time="33.61924695968628">
        
            
            <system-out><![CDATA[
            
            ]]></system-out>
            <system-err><![CDATA[
            
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="samtools_sort (Test #7)" name="6" time="32.6546995639801">
        
            
            <system-out><![CDATA[
            
            ]]></system-out>
            <system-err><![CDATA[
            
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="samtools_sort (Test #8)" name="7" time="33.3199725151062">
        
            
            <system-out><![CDATA[
            
            ]]></system-out>
            <system-err><![CDATA[
            
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="samtools_sort (Test #9)" name="8" time="31.284484386444092">
        
            
            <system-out><![CDATA[
            
            ]]></system-out>
            <system-err><![CDATA[
            
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="vcfallelicprimitives (Test #1)" name="0" time="40.20941114425659">
        
            
            <system-out><![CDATA[
            
            ]]></system-out>
            <system-err><![CDATA[
            
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="vcfprimers (Test #1)" name="0" time="18.502869367599487">
        
            <error type="error" message="Input staging problem: Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 1434, in verify_tool
    stage_data_in_history(
  File "/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 175, in stage_data_in_history
    staging_interface.handle_jobs()
  File "/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 212, in handle_jobs
    self.galaxy_interactor.wait_for_job(job_response["id"], job_response["history_id"], self.maxseconds)
  File "/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 399, in wait_for_job
    self.wait_for(lambda: self.__job_ready(job_id, history_id), maxseconds=maxseconds)
  File "/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 403, in wait_for
    wait_on(func, what, walltime_exceeded)
  File "/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/wait.py", line 38, in wait_on
    value = function()
            ^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 399, in <lambda>
    self.wait_for(lambda: self.__job_ready(job_id, history_id), maxseconds=maxseconds)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 747, in __job_ready
    return self._state_ready(job_id, error_msg="Job in error state.")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py", line 839, in _state_ready
    raise Exception(
Exception: Job in error state.. tool_id: __DATA_FETCH__, exit_code: None, stderr: .
"><![CDATA[
                { "execution_problem": "Input staging problem: Traceback (most recent call last):\n  File \"/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 1434, in verify_tool\n    stage_data_in_history(\n  File \"/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 175, in stage_data_in_history\n    staging_interface.handle_jobs()\n  File \"/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 212, in handle_jobs\n    self.galaxy_interactor.wait_for_job(job_response[\"id\"], job_response[\"history_id\"], self.maxseconds)\n  File \"/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 399, in wait_for_job\n    self.wait_for(lambda: self.__job_ready(job_id, history_id), maxseconds=maxseconds)\n  File \"/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 403, in wait_for\n    wait_on(func, what, walltime_exceeded)\n  File \"/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/wait.py\", line 38, in wait_on\n    value = function()\n            ^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 399, in \u003clambda\u003e\n    self.wait_for(lambda: self.__job_ready(job_id, history_id), maxseconds=maxseconds)\n                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 747, in __job_ready\n    return self._state_ready(job_id, error_msg=\"Job in error state.\")\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/galaxy/tool_util/verify/interactor.py\", line 839, in _state_ready\n    raise Exception(\nException: Job in error state.. tool_id: __DATA_FETCH__, exit_code: None, stderr: .\n", "status": "error", "test_index": 0, "time_seconds": 18.502869367599487, "tool_id": "vcfprimers", "tool_version": "1.0.0_rc3+galaxy0"}
            ]]></error>
        
    </testcase>
    
</testsuite>